virtualcell/vcell

- pom.xml
- vcell-admin/pom.xml
- vcell-api/pom.xml
- vcell-apiclient/pom.xml
- vcell-client/pom.xml
- vcell-core/pom.xml
- vcell-math/pom.xml
- vcell-server/pom.xml
- vcell-util/pom.xml
- vcell-vmicro/pom.xml
This makes various fixes and improvements to the pom.xml files.
> Clean up the POMs

- vcell-cli-utils/vcell_cli_utils/status.py
@moraru this should correct the log format (closes #110). Please release another version to BioSimulators.
> fix: fixed log format

- pom.xml
- vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java
- vcell-cli/src/main/java/org/vcell/cli/OmexHandler.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/FileFilters.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/SedmlExtensionFilter.java
- vcell-core/src/main/java/cbit/vcell/biomodel/ModelUnitConverter.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlHelper.java
- vcell-core/src/main/java/org/jlibsedml/SEDMLWriter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLUnitTranslator.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-imagej-helper/pom.xml
Getting the most recent master branch before pushing changes to the branch
> Updating LD_updateDatasetStatus_optimization with master

- Dockerfile
Changed poetry installation to use apt instead of curl-ing and running a python script
> Change in poetry installation via docker

- Dockerfile
Fixed issue where poetry environment was lost during conversion from docker to singularity image
> Cli singularity poetry interaction fix

- .gitignore
- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
> Cli biosimulators standards fix

- vcell-cli-utils/vcell_cli_utils/cli.py
- vcell-cli/src/main/java/org/vcell/cli/CLIPythonManager.java
- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
- vcell-cli/src/main/java/org/vcell/cli/biosimulation/BiosimulationsCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
More pulling of branches (with needed fixes) into one branch
> Tidying and logging updates Pt.1

- Dockerfile
- vcell-cli-utils/vcell_cli_utils/cli.py
- vcell-cli/src/main/java/org/vcell/cli/CLIPythonManager.java
- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
- vcell-cli/src/main/java/org/vcell/cli/biosimulation/BiosimulationsCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/PythonCalls.java
Fixes a number of bugs both related to, and unrelated to Biosimulators test suite.
> Cli biosimulators safe

- vcell-core/src/test/java/org/vcell/sbml/SbmlTestSuiteFiles.java
fix to restrict SBML Unit Tests to test cases 0 through 1200
> restrict to passing SBML Test Suite cases

- vcell-admin/src/test/java/org/vcell/sbml/SbmlVcmlConverter.java
- vcell-admin/src/test/java/org/vcell/sbml/test/VCellSBMLSolver.java
- vcell-admin/src/test/java/org/vcell/sbml/test/VCellSedMLSolver.java
- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-cli/src/main/java/org/vcell/cli/sbml/MemoryLogger.java
- vcell-client/src/main/java/cbit/vcell/client/BNGWindowManager.java
- vcell-client/src/main/java/cbit/vcell/client/TranslationLogger.java
- vcell-core/src/main/java/cbit/util/xml/VCLogger.java
- vcell-core/src/main/java/cbit/util/xml/VCLoggerException.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLStandaloneImporter.java
- vcell-core/src/test/java/org/vcell/sbml/TLogger.java
- vcell-core/src/test/java/org/vcell/sedml/StandaloneSEDMLTest.java
- vcell-sbmlsim/src/main/java/org/vcell/sbmlsim/service/SimulationServiceImpl.java
This will need more work in the future; a lot of cleanup is needed to fix the prevalent misuse of exceptions.
> Added custom Exception VCLoggerException and refactored accordingly

- biosimulations_log4j2.xml
- vcell-cli/src/main/java/org/vcell/cli/CLIPythonManager.java
- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
- vcell-cli/src/main/java/org/vcell/cli/biosimulation/BiosimulationsCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlHelper.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/main/java/org/vcell/util/exe/Executable.java
Turns out, jsbml had our debug flag bug documented as an existing issue (they've fixed it since, but for one reason or another we don't have that fix; possibly not on release / our version?). To get around it, the log4j2 configuration file was updated; ***please note this file is not read without the following vmarg:*** 
-Dlog4j.configurationFile={path_to_vcell_installDir}/biosimulations_log4j2.xml
This will finally allow us to debug to our full potential.
> Cli logging upgrade

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-core/src/main/java/cbit/util/xml/XmlRdfUtil.java
- vcell-core/src/main/java/cbit/vcell/mapping/BioEvent.java
- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
- vcell-core/src/main/java/org/jlibsedml/modelsupport/SBMLSupport.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
This contains the following fixes:
Rdf metadata stub for exporting to omex from the vcell client.
Error issue for bioevent trigger at time 0.
Error issue when the simulation has unused math overrides.
Detect in CLI the existence of unused math overrides.
Creating new XPath for some spatial parameters.
Bogus compartment size were exported to SBML when spatial.
> Dan working

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
> Call the general metadata creation stub.

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
Builds a list of all public models in the vcell database, builds the URL for each, extracts them all and saves them as files.
> Extract all public models from the vcell DB and store them as .vcml

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-client/src/main/java/cbit/vcell/client/task/SetMathDescription.java
- vcell-core/src/main/java/cbit/vcell/mapping/AbstractMathMapping.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
Prevents saving a model when orphaned Math Overrides are detected.
> Orphan overrides vcell client

- vcell-core/src/main/java/cbit/vcell/mapping/ParticleMathMapping.java
- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/org/vcell/sbml/UnsupportedSbmlExportException.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
> 326 sbml validate applications

- vcell-admin/src/test/java/org/vcell/sbml/SbmlVcmlConverter.java
- vcell-admin/src/test/java/org/vcell/sbml/test/VCellSBMLSolver.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/microscopy/FRAPStudy.java
- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
- vcell-core/src/main/java/cbit/vcell/solver/SimulationOwner.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/main/java/org/vcell/optimization/OptXmlWriter.java
- vcell-core/src/main/java/org/vcell/optimization/ParameterEstimationTaskSimulatorIDA.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
- vcell-vmicro/src/main/java/org/vcell/vmicro/op/Generate2DExpModelOpAbstract.java
- vcell-vmicro/src/main/java/org/vcell/vmicro/op/Generate2DSimBioModelOp.java
- vcell-vmicro/src/main/java/org/vcell/vmicro/op/RunRefSimulationFastOp.java
- vcell-vmicro/src/main/java/org/vcell/vmicro/op/RunRefSimulationOp.java
> 328 omex export npes

- vcell-core/src/main/java/cbit/vcell/solver/ConstantArraySpec.java
- vcell-core/src/test/java/cbit/vcell/solver/MathOverridesTest.java
> quoted expressions in database string for list-type MathOverrides

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
> retain default BC types for CSG & Image geometries during SBML roundtrip

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
see #341 
when exporting SBML, need to combine A + A --> B to form 2A --> B
This problem manifests itself as a non-unique reaction participant id in JSBML - but it is not allowed by SBML spec anyway.
> combine repeated reactants or products for SBML export

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/SedmlExtensionFilter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLConversion.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLLogger.java
- vcell-core/src/main/java/org/vcell/sedml/TaskResult.java
- vcell-core/src/main/java/org/vcell/sedml/TaskType.java
Add task logging for SEDML conversions
Export logging completed
Output format now CSV, JSON and other later
Make visible and use in batch conversions
> Sedml ogging

- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
- vcell-client/src/main/java/cbit/vcell/client/task/ExportDocument.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/MatlabExtensionFilter.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/mathmodel/MathModel.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
- vcell-core/src/main/java/cbit/vcell/solver/SimulationSymbolTable.java
- vcell-core/src/main/java/cbit/vcell/solver/test/MathTestingUtilities.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/main/java/org/vcell/optimization/OptXmlWriter.java
- vcell-core/src/main/java/org/vcell/optimization/ParameterEstimationTaskSimulatorIDA.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/BioModelTest.java
- vcell-core/src/test/java/org/vcell/sedml/StandaloneSEDMLTest.java
> fix dropped math override on vcml load

- vcell-cli-utils/vcell_cli_utils/cli.py
- vcell-cli/src/main/java/org/vcell/cli/run/RunUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
Creating the .csv files, the hdf5 file and plots for parameter scans (repeated tasks) using the existing python code (adapted) 
This is a temporary solution to allow batch testing for published / public models. However, the datasets are flat.
> Dan repeated tasks3

- vcell-core/src/main/java/cbit/vcell/mapping/DiffEquMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/ParticleMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/RulebasedMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/StochMathMapping.java
- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/cbit/vcell/math/Variable.java
- vcell-core/src/main/java/cbit/vcell/solver/ode/SensVariable.java
- vcell-core/src/main/java/cbit/vcell/solver/test/MathTestingUtilities.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
> 387 unbound constants flag invalid

- vcell-core/src/main/java/cbit/vcell/mapping/BioEvent.java
see #391 
BioEvents.gatherIssues() needed to be refactored and made more complete.  It failed on ListOfTimes trigger type with a NPE when looking for an inappropriate parameter type.
Method was refactored to extract the method which substitutes initial conditions and checks for negative or zero values for trigger parameters.
> refactor and extend BioEvents.gatherIssues() - fix NPE

- vcell-core/src/main/java/cbit/vcell/mapping/DiffEquMathMapping.java
> 397: fix unbound var exception for fast system in math gen

- vcell-core/src/main/java/org/jlibsedml/NamespaceContextHelper.java
- vcell-core/src/main/java/org/jlibsedml/SEDMLDocument.java
- vcell-core/src/main/java/org/jlibsedml/execution/ModelResolver.java
> Fixed COPASI collision when attempting to map prefix to URI in jlibsedml

- vcell-core/src/main/java/cbit/vcell/geometry/GeometrySpec.java
- vcell-util/src/main/java/org/vcell/util/Origin.java
> fix round-trip fails for geometry Origin (for 2D, don't compare z)

- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/cbit/vcell/model/DistributedKinetics.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLUnitTranslator.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
- vcell-core/src/test/java/org/vcell/sbml/VcmlTestSuiteFiles.java
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/lumped_reaction_local_size_in_rate.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/lumped_reaction_no_size_in_rate.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/lumped_reaction_proper_size_in_rate.vcml
- vcell-math/src/main/java/cbit/vcell/matrix/RationalExp.java
- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionTest.java
> Fix lumped reaction SBML import

- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverDescription.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverUtilities.java
- vcell-core/src/main/java/org/jlibsedml/Simulation.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
Added support for reading ALGORITHM_SUBSTITUTION_POLICY env variable used by BSTS for their SupportAlgorithmSubstitution test.
closes #418
> Added env-var reading for BSTS tests regarding substituting algorithms.

- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionTest.java
> ExpressionUtil.getLinearFactor() works with inequalities.

- vcell-core/src/main/java/cbit/vcell/model/ModelRelationVisitor.java
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
> reduced logging for Expression and ModelRelationVisitor

- vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ExportOmexBatchCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ExportOmexCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ImportOmexBatchCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ImportOmexCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
added import-omex and import-omex-batch commands to CLI.
Current status - commands stubbed out, need implementation from @moraru in VcmlOmexConverter.java.
> 380 import omex commands

- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/RunUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-cli/src/main/java/org/vcell/cli/run/TaskJob.java
- vcell-core/src/main/java/cbit/vcell/biomodel/ModelUnitConverter.java
Running chained Repeated tasks.
> Dan repeated tasks5

- vcell-cli/src/main/java/org/vcell/cli/run/RunUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
Switching from using the actual task to the topmost task as the simulation's imported task id.
> Dan repeated tasks6

- vcell-core/src/main/java/cbit/vcell/biomodel/ModelUnitConverter.java
- vcell-core/src/main/java/cbit/vcell/xml/XMLTags.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
Added importedTaskIdTag to Simulation XmlReader / Xmlproducer.
> Dan repeated tasks7

- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-util/src/main/java/org/vcell/util/recording/VCellRecordManager.java
> Attempting to fix accidentally deleted files

- vcell-math/src/main/java/cbit/vcell/parser/ExpressionMathMLPrinter.java
- vcell-math/src/main/java/org/jmathml/ASTFunction.java
- vcell-math/src/main/java/org/jmathml/ASTNumber.java
- vcell-math/src/main/java/org/jmathml/ASTToXMLElementVisitor.java
- vcell-math/src/main/java/org/jmathml/ENotationNumber.java
- vcell-math/src/main/java/org/jmathml/MathMLReader.java
- vcell-math/src/test/java/cbit/vcell/parser/MathMLTester.java
> test and correct remaining JMathML problems

- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/RunUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5DatasetMetadata.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5DatasetWrapper.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5FileWrapper.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5JobData.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5Writer.java
- vcell-cli/src/test/java/org/vcell/cli/run/hdf5/Hdf5WriterTest.java
> 439 sedml hdf5 nonspatial scans

- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/RunUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5Writer.java
> 460 fix nonspatial omex

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
> Support sampleField numSamples components per geometry dimension

- vcell-core/src/main/java/cbit/vcell/solver/SolverDescription.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
- vcell-util/src/main/java/org/vcell/util/ISize.java
> temporarily encode MeshSize as KISAO_0000326 in SEDML export/import

- vcell-cli/src/main/java/org/vcell/cli/biosimulation/BiosimulationsCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-cli/src/test/java/org/vcell/cli/run/ExecuteImplTest.java
> add --small-mesh override to CLI execute command (limits to 11x11x11).

- vcell-cli-utils/vcell_cli_utils/status.py
- vcell-cli/src/main/java/org/vcell/cli/biosimulation/BiosimulationsCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-cli/src/main/java/org/vcell/cli/run/Status.java
- vcell-cli/src/test/java/org/vcell/cli/run/ExecuteImplTest.java
- vcell-core/src/main/java/cbit/vcell/simdata/Hdf5Utils.java
Adds "RUNNING" statuses to status yaml/json files 
closes 481
> added more updates to YAML/JSON logs

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
diffusion, advection, boundary conditions parameters
> We don't export some parameters to SBML if the species is clamped.

- vcell-core/src/main/java/cbit/vcell/mapping/AbstractMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/DiffEquMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/GeometryContext.java
- vcell-core/src/main/java/cbit/vcell/mapping/LegacySimContextTransformer.java
- vcell-core/src/main/java/cbit/vcell/mapping/StructureMapping.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/StructureSizeSolver.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
- vcell-core/src/test/java/org/vcell/sbml/StructureSizeSolverTest.java
- vcell-core/src/test/java/org/vcell/sbml/VcmlTestSuiteFiles.java
- vcell-core/src/test/resources/org/vcell/sbml/vcml_published/biomodel_89712092_simple.vcml
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
> Keep SV ratios and VolFracts in math generation for legacy models

- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/RunUtils.java
- vcell-core/src/main/java/org/jlibsedml/RepeatedTask.java
- vcell-core/src/main/java/org/jlibsedml/SEDMLReader.java
Issue is not technically fixed, but see #498. We've gone as far as we're willing to go at this point.
closes #496
> Increased debug ability and cleaned up part of RunUtils

- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
Fix for #507 tested against all published models.
> Deal with varname vs varname_init math side naming in overrides for

- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
> remove passing SEDML exports from knownFaults list - fixes CI failures.

- vcell-server/src/main/java/cbit/vcell/message/server/htc/HtcProxy.java
Lets make sure Kelvin's job runs
> Upgrade poweruser memory to 50GB

- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
Fixes for #513 as well as for other bugs found while working on that one (#514 and #516)
> 513 species init assignment

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
> fix namescope for compartment size STE lookup

- vcell-api/src/main/java/org/vcell/rest/VCellApiApplication.java
- vcell-api/src/main/java/org/vcell/rest/VCellApiMain.java
- vcell-api/src/main/java/org/vcell/rest/server/RestDatabaseService.java
- vcell-api/src/main/java/org/vcell/rest/users/ContactUsRestlet.java
- vcell-client/src/main/java/cbit/vcell/client/test/VCellClientTest.java
- vcell-core/src/main/java/cbit/vcell/resource/ErrorUtils.java
- vcell-core/src/test/java/cbit/vcell/resource/ErrorUtilsTest.java
> initial pass at /contactus endpoint in vcell-api with Dan

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLUnitTranslator.java
> consistent name mangling to generate SBML unit ids.

- vcell-core/src/test/java/org/vcell/sbml/VcmlTestSuiteFiles.java
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_111113048_smaller.vcml
- vcell-math/src/main/java/cbit/vcell/parser/ASTFuncNode.java
- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionTest.java
> expr equiv() supports user-def functions (e.g. vcRegionVolume(LITERAL))

- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/cbit/vcell/math/PdeEquation.java
> ignore 3D equation terms in 2D math compare

- vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ValidateBatchCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlValidator.java
- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
> CLI validate-batch to validate VCML files (compare math generation)

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
Duplicated sid caused by mangling of entities with a name pattern like "a-b" when another entity is named "a_b".
> Dan duplicate id bugs

- vcell-cli/src/main/resources/log4j2.xml
- vcell-server/src/main/java/cbit/sql/CompareDatabaseSchema.java
- vcell-server/src/main/java/cbit/vcell/messaging/db/SimulationJobDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/BioModelDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/BioModelTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/DatabasePolicySQL.java
- vcell-server/src/main/java/cbit/vcell/modeldb/DatabaseServerImpl.java
- vcell-server/src/main/java/cbit/vcell/modeldb/DbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/GeomDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/GeometryTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/ImageTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/MathDescTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/MathDescriptionDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/MathModelDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/MathModelTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/ModelDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/ModelTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/ReactStepTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SQLCreateAllTables.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SimContextTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SimulationContextDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SimulationDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SimulationTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/UserDbDriver.java
see #548
@moraru can this go into 7.5.0?
> 548 support oracle and postgres

- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverridesResolver.java
- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
- vcell-core/src/test/java/cbit/vcell/biomodel/ModelUnitConverterTest.java
> only transform units on setting math on Simulation

- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
> write/read to/from VCML membrane boundary conditions; fixes #570

- vcell-cli/src/main/java/org/vcell/cli/vcml/ValidateBatchCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlValidator.java
> toggle changes to KMOLE and variable names while validating math

- Dockerfile
> add Bionetgen to biosimulators_vcell for rule-based model validation

- vcell-server/src/main/java/cbit/vcell/modeldb/AdminDBTopLevel.java
- vcell-server/src/main/java/cbit/vcell/modeldb/DBTopLevel.java
- vcell-server/src/main/java/cbit/vcell/modeldb/DbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SQLCreateAllTables.java
- vcell-server/src/main/java/org/vcell/db/postgres/PostgresKeyFactory.java
- vcell-server/src/main/java/org/vcell/pub/VCellPubUtils.java
#583 
got in the way of local vcell debugging using locally installed Postgres
> 583 more postgres syntax

- vcell-client/src/main/java/cbit/vcell/client/data/PDEDataViewer.java
- vcell-client/src/main/java/cbit/vcell/simdata/gui/PDEDataContextPanel.java
- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/ODESolverPlotSpecificationPanel.java
- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/OutputSpeciesResultsPanel.java
- vcell-server/src/main/java/cbit/vcell/modeldb/DbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/MathVerifier.java
#588 
UI and database fixes for Math Testing Framework GUI operation.
> 588 UI fixes mathtestingframework

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
> keep SBML global and reaction namespaces separate in SBMLImporter

- vcell-admin/src/main/java/org/vcell/admin/cli/AdminCLI.java
- vcell-admin/src/main/java/org/vcell/admin/cli/CLIDatabaseService.java
- vcell-admin/src/main/java/org/vcell/admin/cli/db/DatabaseCompareSchemaCommand.java
- vcell-admin/src/main/java/org/vcell/admin/cli/db/DatabaseDestroyAndRecreateCommand.java
- vcell-admin/src/main/java/org/vcell/admin/cli/mathverifier/ModeldbLoadTestCommand.java
- vcell-admin/src/main/java/org/vcell/admin/cli/mathverifier/ModeldbMathGenTestCommand.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-server/src/main/java/cbit/sql/CompareDatabaseSchema.java
- vcell-server/src/main/java/cbit/vcell/modeldb/AnalysisTaskXMLTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/DbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/LoadModelsStatTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/MathVerifier.java
- vcell-server/src/main/java/cbit/vcell/modeldb/ResultSetMetaDataTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SQLCreateAllTables.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SimContextStat2Table.java
- vcell-server/src/main/java/cbit/vcell/modeldb/TFTestCaseTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/TFTestCriteriaTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/TFTestResultTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/TFTestSuiteTable.java
> 595 revive load and mathgen tests

- vcell-core/src/main/java/cbit/vcell/mapping/StructureMapping.java
> fix other place where structure parameters are not bound to simContext

- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-core/src/main/java/cbit/util/xml/XmlUtil.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModel.java
- vcell-core/src/main/java/cbit/vcell/mapping/AbstractMathMapping.java
- vcell-core/src/main/java/cbit/vcell/model/Structure.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/MathOverrideRoundTipTest.java
- vcell-core/src/test/resources/cbit/vcell/biomodel/Biomodel_issue_554.vcml
- vcell-core/src/test/resources/cbit/vcell/biomodel/Biomodel_issue_554_r0.vcml
- vcell-core/src/test/resources/cbit/vcell/biomodel/Biomodel_issue_554_r0_r1.vcml
- vcell-core/src/test/resources/cbit/vcell/biomodel/Biomodel_issue_554_r1.vcml
- vcell-core/src/test/resources/cbit/vcell/biomodel/Biomodel_issue_554_r2.vcml
- vcell-core/src/test/resources/cbit/vcell/biomodel/Biomodel_issue_554_r2_r3.vcml
- vcell-core/src/test/resources/cbit/vcell/biomodel/Biomodel_issue_554_r3.vcml
> 554 convert reaction orphans overrides

- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/MathOverrideRoundTipTest.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
> SEDMLExporterTest writes/reads omex and verifies 1 BioModel returned.

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLSymbolMapping.java
Fixes #598 Error in SBML export
> 598 dan roundtrip fail

- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
> acknowledging that two sedml tests pass - fixed CI failure.

- vcell-apiclient/src/main/java/org/vcell/api/client/VCellApiClient.java
- vcell-apiclient/src/main/java/org/vcell/api/client/examples/VCSchedulerPanel.java
- vcell-apiclient/src/main/java/org/vcell/api/client/examples/VCellApiClientTest.java
- vcell-core/src/main/java/cbit/vcell/message/server/bootstrap/client/RemoteProxyVCellConnectionFactory.java
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
- vcell-core/src/main/java/org/vcell/optimization/CopasiOptimizationSolver.java
- vcell-core/src/main/java/org/vcell/service/registration/remote/RemoteRegistrationService.java
> added vcell.ssl.ignoreHostMismatch,vcell.ssl.ignoreCertProblems [=false]

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLUnitTranslator.java
- vcell-core/src/test/java/org/vcell/sbml/SBMLUnitTranslatorTest.java
> set SBML Unit sid always

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
> roundtrip reserved parameters

- vcell-core/src/main/java/org/jlibsedml/SEDMLWriter.java
FunctionalRange creates empty lists #649
> Do not export to SedML empty lists for FunctionalRange.

- vcell-core/src/main/java/org/jlibsedml/SEDMLWriter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
Replace deprecated SEDBase methods addNote() and getNotes(), use instead the sedml L1V2 and up methods.
We show the description of kisao terms for AlgorithmParameters as notes.
> Dan sedml notes

- .github/workflows/ci_cd.yml
- pythonProject/vcell-opt/tests/vcellopt_test.py
> execute parameter estimation pytest in CI

- .github/workflows/ci_cd.yml
- docker/build/build.sh
> minor CI fixes for optimization build/deploy

- .github/workflows/site_deploy.yml
- docker/swarm/deploy-action.sh
> final deploy step needs to work with both singularity images.

- docker/build/Dockerfile-api-dev
- vcell-api/src/main/java/org/vcell/rest/VCellApiMain.java
- vcell-api/src/main/java/org/vcell/rest/server/OptimizationRunServerResource.java
> calculate vcell-submit service name in cluster env for optimization comm

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlValidator.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModelTransforms.java
- vcell-core/src/test/java/cbit/vcell/mapping/MathGenCompareTest.java
> reusable KMOLE transform, math equiv unit test for published models.

- vcell-admin/src/main/java/org/vcell/admin/cli/CLIDatabaseService.java
- vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/DatabaseCommand.java
> 691 vcml download cli command

- vcell-client/src/main/java/cbit/vcell/client/task/ChooseFile.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/SedmlExtensionFilter.java
Using overriden SedmlExtensionFilter.requiresMoreChoices() and askUser() invoked in ChooseFile
> Refactoring choosing between export to sedml as vcml vs sbml.

- docker/swarm/deploy.sh
- docker/swarm/docker-compose.yml
- docker/swarm/link-installers.sh
- vcell-api/src/main/java/org/vcell/rest/UserVerifier.java
- vcell-api/src/main/java/org/vcell/rest/VCellApiApplication.java
> 703 fix endpoint permissions

- pythonProject/vcell-opt/README.md
- vcell-server/src/main/java/cbit/vcell/modeldb/BioModelDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/BioModelTable.java
- vcell-server/src/main/java/cbit/vcell/modeldb/PublicationTable.java
> 709 api endpoint compat

- vcell-client/src/main/java/cbit/plot/gui/Plot2DDataPanel.java
- vcell-client/src/main/java/cbit/vcell/client/data/ODETimePlotMultipleScansPanel.java
- vcell-client/src/main/java/cbit/vcell/client/data/SimResultsViewer.java
- vcell-core/src/main/java/cbit/plot/Plot2D.java
Enable export of stochastic simulations results with parameter scans
> Dan stochastic overrides

- docker/swarm/deploy-action.sh
> correct singularity image scp command and add error handling

- vcell-core/src/main/java/org/jlibsedml/execution/ModelResolver.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
> 720 vcml sedml export testing

- biosimulations_log4j2.xml
- docker/build/vcell-api.log4j.xml
- docker/build/vcell-batch.log4j.xml
- docker/build/vcell-data.log4j.xml
- docker/build/vcell-db.log4j.xml
- docker/build/vcell-opt.log4j.xml
- docker/build/vcell-sched.log4j.xml
- docker/build/vcell-submit.log4j.xml
- vcell-cli/src/main/resources/log4j2.xml
- vcell-core/src/main/java/cbit/vcell/mongodb/VCMongoDbDriver.java
- vcell-core/src/main/java/cbit/vcell/mongodb/VCMongoMessage.java
- vcell-util/pom.xml
- vcell-util/src/main/resources/EcsLayout.json
minor adjustments to VCMongoMessage and VCMongoDbDriver to provide pure JSON structured logs to ElasticStack.  More refactoring needed to take advantage of log correlation in a systematic way using extensive use of Log4J ThreadContext.
> 724 structured logging phase 1

- vcell-core/src/main/java/cbit/vcell/model/ReactionStep.java
> Removed bad warning for mass action degradation reaction Issue #730

- vcell-core/src/main/java/cbit/vcell/solver/ConstantArraySpec.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterCommon.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterSBMLTest.java
> 731 fix sedml mathoverride tests

- vcell-core/src/main/java/cbit/vcell/mapping/MicroscopeMeasurement.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
> Microscope protocol not copied together with the application

- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
> Dealing with negative or zero diffusion coefficients.

- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
When the old diffusion coefficient is zero.
> Wrong initialization of diffusion coefficient during copy application.

- vcell-api/src/main/java/org/vcell/rest/VCellApiApplication.java
> vcell-api return software-version with URL path / for Better Uptime

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/ApplicationSpecificationsPanel.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/MolecularTypePropertiesPanel.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/SelectionManager.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularTypeSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/SpeciesContextSpecsTableModel.java
- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
Partial layout and data representation. Non functional but stable, won't break alpha.
> Dan springsalad2

- debug_log4j2.xml
- vcell-api/src/main/java/org/vcell/rest/server/OptimizationRunServerResource.java
- vcell-client/src/main/java/org/vcell/optimization/gui/ParameterEstimationRunTaskPanel.java
- vcell-core/src/main/java/org/vcell/optimization/CopasiOptimizationSolver.java
- vcell-core/src/main/java/org/vcell/optimization/CopasiUtils.java
- vcell-core/src/main/java/org/vcell/optimization/ParameterEstimationTaskSimulatorIDA.java
- vcell-server/src/main/java/cbit/vcell/message/server/batch/opt/OptimizationBatchServer.java
> 763 refine parameter estimation feedback

- vcell-client/src/main/resources/vcell_dynamic_properties.csv
> updated COPASI parest URL link (and others)

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlValidator.java
- vcell-client/src/main/java/cbit/vcell/microscopy/gui/DiffOnRateEstimationPanel.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModel.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModelTransforms.java
- vcell-core/src/main/java/cbit/vcell/mapping/vcell_4_8/MembraneStructureAnalyzer.java
- vcell-core/src/main/java/cbit/vcell/mapping/vcell_4_8/StochMathMapping_4_8.java
- vcell-core/src/main/java/cbit/vcell/model/Model.java
- vcell-core/src/test/java/cbit/vcell/mapping/MathGenCompareTest.java
- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
> 738 inconsistent geometry sizes

- .gitignore
- vcell-admin/src/main/java/org/vcell/admin/cli/CLIDatabaseService.java
- vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/DatabaseCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlValidator.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModelTransforms.java
- vcell-core/src/main/java/cbit/vcell/math/MathCompareResults.java
- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/cbit/vcell/math/ParticleJumpProcess.java
- vcell-core/src/main/java/org/vcell/util/document/GroupAccessSome.java
- vcell-core/src/test/java/cbit/vcell/mapping/MathGenCompareTest.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterSBMLTest.java
- vcell-core/src/test/java/org/vcell/sbml/VcmlTestSuiteFiles.java
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_83462243.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_83651737.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_97075423.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_97705317.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_97786619.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_97786886.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_97787114.vcml
- vcell-core/src/test/resources/org/vcell/sbml/vcml_testmodels/biomodel_98730962.vcml
> 702 nonequiv particle stochastic

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
> Export to SBML only used physical constants.

- .gitignore
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModelTransforms.java
- vcell-core/src/test/java/cbit/vcell/mapping/MathGenCompareTest.java
- vcell-core/src/test/java/org/vcell/sbml/VcmlTestSuiteFiles.java
> added BioModelTransforms.fixLegacyMassAction() with tests from db.

- vcell-admin/src/main/java/org/vcell/admin/cli/sim/SimDataVerifier.java
> Auto stash before checking out "origin/master"

- vcell-core/src/main/java/cbit/vcell/solvers/AbstractCompiledSolver.java
- vcell-core/src/main/java/cbit/vcell/solvers/FiniteVolumeFileWriter.java
- vcell-core/src/main/java/cbit/vcell/solvers/FunctionFileGenerator.java
> catch exception when time discontinuities are not simple.

- vcell-api/src/main/java/org/vcell/rest/server/BiomodelSBMLServerResource.java
- vcell-cli/src/main/java/org/vcell/cli/sbml/ModelCommand.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/SbmlExtensionFilter.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModel.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModelTransforms.java
- vcell-core/src/main/java/cbit/vcell/solver/SimulationSymbolTable.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlHelper.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/MathOverrideApplyTest.java
- vcell-core/src/test/java/org/vcell/sbml/SBMLSpatialTest.java
> 793 sbml export from gui with apply overrides in BioModel

- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
When trying to use the SBML name instead the SBML id as VCell name
> BMDB import adding 1 at the end of some names.

- docker/build/Dockerfile-batch-dev
- docker/build/Dockerfile-submit-dev
- docker/build/build.sh
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
- vcell-server/src/main/java/cbit/vcell/message/server/htc/slurm/SlurmProxy.java
> 806 vcell batch archive simdatadir

- vcell-client/src/main/java/cbit/vcell/client/data/SimulationWorkspaceModelInfo.java
> catch all exceptions to not abort viewing data.

- vcell-client/src/main/java/cbit/vcell/graph/gui/ReactionCartoonTool.java
Works by invoking multiple times the single reaction copy and paste dialog, far from ideal solution
Behavior insufficiently tested in complex scenarios.
Fixed in commit d929cbb
> Copy and paste multiple reactions now working.

- docker/build/Dockerfile-data-dev
- docker/build/Dockerfile-web-dev
- docker/build/vcell-admin.log4j.xml
- docker/build/vcell-api.log4j.xml
- docker/build/vcell-batch.log4j.xml
- docker/build/vcell-data.log4j.xml
- docker/build/vcell-db.log4j.xml
- docker/build/vcell-opt.log4j.xml
- docker/build/vcell-sched.log4j.xml
- docker/build/vcell-submit.log4j.xml
- docker/build/vcell-web.log4j.xml
- docker/swarm/docker-compose.yml
- vcell-util/src/main/resources/VCellEcsLayout.json
> 823 fix vcell web config

- .github/workflows/site_deploy.yml
- docker/build/admin/vcell-su.sh
- vcell-admin/src/main/java/org/vcell/admin/cli/db/DatabaseDestroyAndRecreateCommand.java
> deploy vcell-su CLI as a usable script

- vcell-core/src/main/java/cbit/vcell/biomodel/meta/VCMetaDataMiriamManager.java
> Added FlyBase database for Annotations.

- vcell-server/src/main/java/cbit/vcell/modeldb/ServerDocumentManager.java
> fixed NPE while resaving a biomodel where original cannot be loaded.

- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
see #860
exports sbml InitialAssignments when AssignmentRules are needed for clamped Species and non-constant Parameters.
> exports sbml InitialAssignments when AssignmentRules are needed

- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/RunUtils.java
closes #871 ; This passed BSTS microservice.
> Singularity fix

- docker/build/Dockerfile-admin-dev
- docker/build/Dockerfile-sched-dev
- docker/build/Dockerfile-submit-dev
- docker/build/admin/entrypoint.sh
- vcell-admin/src/main/java/org/vcell/admin/cli/AdminCLI.java
- vcell-admin/src/main/java/org/vcell/admin/cli/CLIDatabaseService.java
- vcell-admin/src/main/java/org/vcell/admin/cli/sim/JobAdmin.java
- vcell-admin/src/main/java/org/vcell/admin/cli/sim/JobInfoCommand.java
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
- vcell-server/src/main/java/cbit/vcell/message/server/batch/sim/HtcSimulationWorker.java
- vcell-server/src/main/java/cbit/vcell/message/server/dispatcher/BatchScheduler.java
- vcell-server/src/main/java/cbit/vcell/message/server/dispatcher/SimulationDispatcher.java
- vcell-server/src/main/java/cbit/vcell/message/server/htc/slurm/SlurmProxy.java
- vcell-server/src/test/java/cbit/vcell/message/server/dispatcher/BatchSchedulerTest.java
added vcell-su job-info command to get insight into scheduler disposition of all active jobs.
> 884 log waiting jobs

- vcell-cli-utils/poetry.lock
- vcell-cli-utils/pyproject.toml
> update to biosimulator_utils 0.1.180 and kisao 2.3.2

- vcell-core/src/main/resources/kisao_algs.obo
- vcell-core/src/main/resources/kisao_algs_20230623_old.obo
> Update to the latest kisao ontology.

- vcell-cli-utils/vcell_pipeline/download_vcell_omex.py
python script to download omex files from vcell-api failed for large files (most omex files are large).
> fix download_vcell_omex.py to properly download large omex files

- vcell-api/src/main/java/org/vcell/rest/server/BiomodelOMEXServerResource.java
- vcell-api/src/main/java/org/vcell/rest/server/BiomodelSBMLServerResource.java
- vcell-api/src/main/java/org/vcell/rest/server/RestDatabaseService.java
- vcell-cli-utils/vcell_pipeline/download_vcell_omex.py
improve error message for omex export from vcell-api.  previously, the exception message was not forwarded properly to the vcell-api client.
> improve error message for omex export from vcell-api

- vcell-api/src/main/java/org/vcell/rest/server/BiomodelOMEXServerResource.java
- vcell-api/src/main/java/org/vcell/rest/server/RestDatabaseService.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-core/src/main/java/cbit/util/xml/XmlRdfUtil.java
- vcell-core/src/main/java/org/vcell/sedml/PubMet.java
- vcell-core/src/main/java/org/vcell/sedml/PublicationMetadata.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/MathOverrideRoundTipTest.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterCommon.java
- vcell-core/src/test/java/org/vcell/sedml/PublicationMetadataTest.java
> add abstracts in omex

- vcell-core/src/main/java/cbit/vcell/mapping/ParticleMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/test/java/cbit/vcell/biomodel/ModelCountAndConcentrationTest.java
- vcell-core/src/test/resources/cbit/vcell/biomodel/Stoch_spatial_conc.vcml
- vcell-core/src/test/resources/cbit/vcell/biomodel/Stoch_spatial_count.vcml
NPE when converting conc to count and vice-versa for spatial stochastic
> NPE when converting conc to count and vice-versa for spatial stochastic

- vcell-core/src/main/java/org/vcell/pathway/Xref.java
Update reactome old to new id map, access resource as stream instead of file.
branch: Dan-pathway-reactomeid
issue #934
> Update reactome old to new id map, access resource as stream instead of file.

- vcell-admin/src/main/java/org/vcell/admin/cli/sim/SimDataVerifier.java
- vcell-api/src/main/java/org/vcell/rest/VCellApiApplication.java
- vcell-api/src/main/java/org/vcell/rest/admin/AdminStatsRestlet.java
- vcell-api/src/main/java/org/vcell/rest/server/RestDatabaseService.java
- vcell-api/src/main/java/org/vcell/rest/users/LoginFormRestlet.java
- vcell-server/src/main/java/cbit/vcell/message/server/dispatcher/SimulationDatabase.java
- vcell-server/src/main/java/cbit/vcell/message/server/dispatcher/SimulationDatabaseDirect.java
- vcell-server/src/main/java/cbit/vcell/message/server/dispatcher/SimulationDispatcherEngine.java
- vcell-server/src/main/java/cbit/vcell/message/server/dispatcher/SimulationStateMachine.java
- vcell-server/src/main/java/cbit/vcell/modeldb/AdminDBTopLevel.java
- vcell-server/src/main/java/cbit/vcell/modeldb/LocalAdminDbServer.java
see Issue #938 
Replaced old web access to vcell usage with new Restlet with proper authentication/authorization.
> new AdminStats web page

- docker/build/Dockerfile-data-dev
- docker/build/Dockerfile-db-dev
- docker/build/Dockerfile-sched-dev
- docker/build/Dockerfile-submit-dev
- docker/database/backup_scripts/README.md
- docker/database/backup_scripts/archivedb.sh
- docker/database/backup_scripts/move_files_to_vcellhome.sh
https://github.com/virtualcell/vcell/issues/957
https://github.com/virtualcell/vcell/issues/945
Alpine timezone fix (previously applied Debian timezone patch to the alpine Linux containers also).
Updated to latest Oracle Database backup scripts.
> Alpine timezone fix & updated db backup scripts.

- vcell-core/src/main/java/cbit/vcell/simdata/SimulationData.java
> Security vulnerability with sim results path manipulation.

- vcell-server/src/main/java/cbit/vcell/modeldb/DbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/GeomDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/ImageTable.java
- vcell-server/src/main/java/org/vcell/db/migrate/MigrateDbManager.java
see #966 
Oracle LOB and CLOB resources were not being explicitly free'd after retrieving data.
> db browseimage fails

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterSBMLTest.java
> We now can export flattened reaction networks (rule-based but no rules)

- vcell-core/src/main/java/cbit/vcell/export/SpringSaLaDExporter.java
- vcell-core/src/main/java/cbit/vcell/solver/LangevinSimulationOptions.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverTaskDescription.java
- vcell-core/src/main/java/cbit/vcell/xml/XMLTags.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
Implement the XMLProducer for SpringSaLaD specific attributes / fields Issue #970
> Dan ss xmlproducer2

- vcell-client/src/main/java/cbit/vcell/mapping/gui/ModelProcessSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/LangevinOptionsPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/ReactionRuleSpec.java
- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/cbit/vcell/solver/LangevinSimulationOptions.java
- vcell-core/src/main/java/cbit/vcell/xml/XMLTags.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
The XmlReader and XmlProducer are now complete, export to / import from VCML tested for old application types and for springsalad.
> Dan ss xml reader

- vcell-client/src/main/java/cbit/vcell/mapping/gui/ModelProcessSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularTypeSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/LangevinOptionsPanel.java
- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/LangevinMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/MolecularInternalLinkSpec.java
- vcell-core/src/main/java/cbit/vcell/math/LangevinParticleJumpProcess.java
- vcell-core/src/main/java/cbit/vcell/math/VCML.java
- vcell-core/src/main/java/cbit/vcell/solver/LangevinSimulationOptions.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverTaskDescription.java
Consistency before UI and SS memory model.
> Consistency before UI and SS memory model.

- docker/build/installers/VCell.install4j
- docker/build/installers/build_installers.sh
> set explicit client jar list to avoid conflict with previous installs

- docker/build/Dockerfile-batch-dev
> use ghcr.io/virtualcell/vcell-solvers:v0.0.43 base image for solvers

- vcell-admin/src/main/java/org/vcell/standalone/VCellClientDevMain.java
- vcell-core/src/main/java/cbit/vcell/field/FieldFunctionArguments.java
- vcell-core/src/main/java/cbit/vcell/simdata/DataSetControllerImpl.java
- vcell-core/src/main/java/cbit/vcell/simdata/SimulationData.java
- vcell-core/src/main/java/cbit/vcell/solvers/FiniteVolumeFileWriter.java
(see #1006) flatten time expression to number in field filename and .fvinput file
> vcfield accepts time as constant expression

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/BioModelEditorModelPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/ReactionRuleSpec.java
issue SpringSaLaD bug fix, improved robustness #1012
commit 35d2825
> SpringSaLaD related bug fix, robustness

- README.md
- README_BioSim.md
see #422 
The build instructions were updated and tested on Macos.
> update user build instructions for vcell and vcell cli

- vcell-core/src/main/java/cbit/vcell/mapping/SiteAttributesSpec.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
- vcell-core/src/test/java/cbit/vcell/biomodel/SpringSaLaDGoodReactionsTest.java
- vcell-core/src/test/resources/cbit/vcell/biomodel/Spring_application.vcml
- vcell-server/src/main/java/cbit/vcell/modeldb/SimulationContextDbDriver.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SpeciesContextSpecTable.java
SpringSaLaD persistence, SpeciesContextSpecs SQL table implementation 
Issue #1042
> Dan ss persist scs

- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/SpringSaLaDGoodReactionsTest.java
- vcell-core/src/test/resources/cbit/vcell/biomodel/Spring_application.vcml
adjusting the test case to exercise bond length
configuring the tests to run on commit
> Dan ss rule spec

- vcell-core/src/main/java/cbit/vcell/export/SpringSaLaDExporter.java
- vcell-core/src/main/java/cbit/vcell/geometry/GeometrySpec.java
- vcell-core/src/main/java/cbit/vcell/mapping/GeometryContext.java
- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
The langevin input file is now being created exclusively from the Math. 
All references to the simulation context are eliminated.
> Dan ss math model

- vcell-client/src/main/java/cbit/vcell/export/gui/ExportMonitorPanel.java
Copy exported file location to the clipboard.
> Dan export copy menu

- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
- vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataTableModel.java
- vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataViewer.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/DocumentWindow.java
- vcell-core/src/main/java/cbit/vcell/export/server/ExportServiceImpl.java
- vcell-core/src/main/java/cbit/vcell/export/server/N5Exporter.java
A new JDialog is added to the VCell GUI that allows users to the exports they have committed. The export meta-data is saved locally on the users device in the VCell home directory exportMetaData JSON.
> Improve n5 export transition to image j

- docker/swarm/docker-compose-small.yml
Before the main docker compose file didn't expose the N5 data directory for the data service, now it does.
> Fix N5 Data Dir Internal Error

- .gitignore
- docker/build/Dockerfile-batch-dev
- exampleModels/SpringSalad_SolverSuite.vcml
- vcell-core/pom.xml
- vcell-core/src/main/java/cbit/vcell/solver/SolverExecutable.java
> install springsalad localsolvers

- exampleModels/SpringSalad_SolverSuite.vcml
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
Simple binding reaction, gramatically correct
Bug fixing related to langevin input file creation for binding reactions
> Solver suite compatible with SpringSaLaD

- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularTypeSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/SpeciesContextSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/math/gui/MathDescEditor.java
- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/AbstractStochMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/LangevinMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
- vcell-core/src/main/java/cbit/vcell/math/LangevinParticleMolecularType.java
- vcell-core/src/main/java/cbit/vcell/math/VCML.java
- vcell-core/src/main/java/cbit/vcell/xml/XMLTags.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
Added is2D flag to the UI and internal representation
Note: for now we shoult use it as always false, until we check the solver code and understand its meaning / correctness
domain name bug fixed in the math
> Added is2D flag, domain name bug fixed in the math

- vcell-cli/src/main/java/org/vcell/cli/biosimulation/BiosimulationsCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/SedmlJob.java
- vcell-cli/src/main/java/org/vcell/cli/run/SolverHandler.java
- vcell-cli/src/main/java/org/vcell/cli/trace/Span.java
- vcell-cli/src/main/java/org/vcell/cli/trace/TraceEvent.java
- vcell-cli/src/main/java/org/vcell/cli/trace/Tracer.java
- vcell-cli/src/test/java/org/vcell/cli/trace/TracerTest.java
> trace omex processing to intercept errors for biosimulations-vcell

- .github/workflows/ci_cd.yml
- Dockerfile
- vcell-cli/src/test/java/org/vcell/cli/run/BiosimulationsExecTest.java
- vcell-core/pom.xml
The changes needed to get VCell containers with the new solvers working on biosimulators
> Biosimulators upload fixes

- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-core/src/main/java/cbit/vcell/math/LangevinParticleMolecularType.java
Added 'Delete Link' button to the Molecular Structures Panel
Fix math parsing error
> Springsalad UI and math parser improvements and bug fixing

- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
eliminating parasitic sim owner references causing NPE for green button
> eliminating parasitic sim owner references causing NPE for green button

- python-utils/tests/citation_test.py
- python-utils/vcutils/biosim_pipeline/README.md
- python-utils/vcutils/biosim_pipeline/biosim_api.py
- python-utils/vcutils/biosim_pipeline/main.py
- python-utils/vcutils/vcell_pipeline/datamodels.py
- python-utils/vcutils/vcell_pipeline/download_biosim_projects.py
- python-utils/vcutils/vcell_pipeline/download_sim_run.py
- python-utils/vcutils/vcell_pipeline/download_vcell_omex.py
- vcell-cli/src/main/java/org/vcell/cli/trace/Span.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ExportOmexBatchCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ExportOmexCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-core/src/main/java/org/vcell/sedml/PublicationMetadata.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/test/java/org/vcell/sedml/PublicationMetadataTest.java
> 1126 export omex with pubmed

- vcell-core/pom.xml
> upgrade Macos solvers to fix NFSim failure

- pom.xml
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/BioModelEditorApplicationsPanel.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/DocumentEditor.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModel.java
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
- vcell-core/src/main/java/cbit/vcell/simdata/SimulationData.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinPostprocessor.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinSolver.java
- vcell-core/src/test/java/org/vcell/solver/langevin/LangevinPostprocessorTest.java
- vcell-core/src/test/resources/cbit/vcell/biomodel/Spring_simulation_transition.vcml
see #1135 
This PR has been rescoped to provide necessary but not sufficient changes to enable remote simulation of Langevin solver.  There have been improvements to the local solver execution and Langevin solver input processing.
> Fixes for langevin solver

- vcell-core/src/main/java/cbit/vcell/export/server/N5Exporter.java
- vcell-core/src/test/java/cbit/vcell/export/N5ExporterTest.java
Instead of having the time name start at the index in the time array, it'll start at 0 and increase from there.
> Normalize Time Index

- biosimulations_log4j2.xml
- debug_log4j2.xml
- vcell-cli/src/main/java/org/vcell/cli/biosimulation/BiosimulationsCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/RunUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/SedmlJob.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5DataExtractor.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5DataSourceSpatialVarDataItem.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/NonspatialResultsConverter.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/SpatialResultsConverter.java
Makes clearer error messages when hdf5 results code can not find the needed data
> Finding spatial data

- pom.xml
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinSolver.java
see https://github.com/cam-center/LangevinNoVis01/pull/6
> fix langevin status reporting

- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularTypeSpecsTableModel.java
- vcell-core/src/main/java/cbit/vcell/mapping/LangevinMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/SiteAttributesSpec.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
Converging the concept of Anchoring across SpringSalad and Rule Based Modeling
Strict consistency verifications for MolecularComponentPatterns instances across site attributes map and internal link set vs the authoritative MolecularComponentPatterns instances in the species context -> species pattern -> molecular type pattern -> molecular component pattern
> Better anchor requirements, inconsistent data strict detection

- docker/README_Oracle.md
- docker/swarm/README_certs_install.md
- docker/swarm/serverconfig-uch.sh
> update test site config and database documentation

- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-core/src/main/java/org/vcell/util/exe/Executable.java
> fix local solver timeout for rule based models

- vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataViewer.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/DocumentWindow.java
Export viewer UI candidate
part of Epic: Final Refinments to N5 Export #31
> Dan exporter UI

- vcell-core/src/main/java/cbit/vcell/simdata/DataServerImpl.java
- vcell-server/src/main/java/cbit/vcell/message/server/data/SimDataServerMain.java
Needed to load the HDF Group's C-based library for server functionality
> Hdf5 server fix

- vcell-core/src/main/java/cbit/vcell/export/server/ASCIIExporter.java
- vcell-core/src/main/java/cbit/vcell/export/server/ExportServiceImpl.java
- vcell-core/src/main/java/cbit/vcell/export/server/IMGExporter.java
- vcell-core/src/main/java/cbit/vcell/export/server/JobRequest.java
- vcell-core/src/main/java/cbit/vcell/export/server/N5Exporter.java
- vcell-core/src/main/java/cbit/vcell/export/server/N5Specs.java
- vcell-core/src/main/java/cbit/vcell/export/server/RasterExporter.java
- vcell-core/src/test/java/cbit/vcell/export/N5ExporterTest.java
Have the dataset name be the JobID generated for the users, and the N5 file name hash be truncated.
> JobID for Dataset Name and Truncated URL

- vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataTableModel.java
- vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataViewer.java
- vcell-client/src/main/java/cbit/vcell/export/gui/ExportMonitorPanel.java
- vcell-core/src/main/java/cbit/vcell/export/server/ExportFormat.java
exported data viewer improvements
> Dan exporter2 UI: exported data viewer improvements

- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
- vcell-client/src/main/java/cbit/vcell/export/gui/ExportMonitorPanel.java
- vcell-client/src/main/java/cbit/vcell/export/gui/ExportMonitorTableModel.java
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
> Dan export monitor

- python-utils/vcutils/vcell_pipeline/download_vcell_omex.py
- python-utils/vcutils/vcell_pipeline/rename_vcell_omex.py
- vcell-cli/src/main/java/org/vcell/cli/run/ExecutionJob.java
- vcell-cli/src/main/java/org/vcell/cli/run/SedmlJob.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/HDF5ExecutionResults.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5DataContainer.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5DataExtractor.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5File.java
- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5Writer.java
- vcell-cli/src/test/java/org/vcell/cli/run/hdf5/Hdf5WriterTest.java
- vcell-core/src/main/java/cbit/vcell/biomodel/ModelUnitConverter.java
Two big updates:
- New rename feature in vcell_pipeline to prettily rename models for outside publication.
- Fixed issues with BSTS test failures.
> Fix remaining issues preventing / hindering publishing VCell models on BSTS

- vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataViewer.java
Delete exported data entities from history, manage multiple selections
> Dan export delete

- vcell-client/src/main/java/cbit/vcell/client/DatabaseWindowManager.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/ACLEditor.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/ACLState.java
> fix permissions dialog

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/AnnotationsPanel.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/annotations/AddAnnotationsPanel.java
- vcell-core/src/main/java/cbit/vcell/biomodel/meta/VCMetaDataMiriamManager.java
Bringing Search and Add annotations together
> Dan annotations mix

- vcell-client/src/main/java/cbit/vcell/client/ClientSimManager.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/simulation/SimulationWorkspace.java
- vcell-core/src/main/java/cbit/vcell/resource/ResourceUtil.java
improve batch simulation messaging for both importing overrides file and exporting batch simulation results
Clear confirmation at the end of a run of success or failure, multiple helpful error messages during execution
Logging
> Dan batch messaging

- vcell-core/src/main/java/cbit/vcell/mapping/LangevinMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/MolecularInternalLinkSpec.java
- vcell-core/src/main/java/cbit/vcell/mapping/ReactionContext.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
After editing a molecule / saving the model, the springsalad-specific atributes has duplicated molecular component patterns
> Dan ss duplicates

- vcell-client/src/main/java/cbit/vcell/client/desktop/DocumentWindow.java
> Removed Surpurfluous geometry menu options

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/AnnotationsPanel.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/annotations/AddAnnotationsPanel.java
Delete disabled and non-functional because of NPEs
Added URL and Description to the Search panel
> AnnotationsPanel: Fix multiple null pointer exceptions

- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/DocumentWindow.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/BioModelEditorAnnotationPanel.java
- vcell-client/src/main/java/cbit/vcell/desktop/ClientLogin.java
Two improvements have been made:
1) Messages in all login / logout dialogs have been clarified for formatted for appearances.
2) VCell now offers a separate "Account"->"Login as Guest" option in the `Account` menu, to login as guest without needing to restart VCell. "Account"->"Login" now also immediately redirects to Auth0, as the choices are now redundant.
> Final GUI changes

- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
Throw exception if file format is null
> Saving to ExportMetaData json file is more error tolerant now.

- pom.xml
- vcell-rest/pom.xml
- vcell-rest/src/main/resources/application.properties
> add structured logging using elastic common schema to quarkus vcell-rest

- vcell-admin/src/test/java/cbit/vcell/util/TestMissingSimData.java
- vcell-api/src/main/java/org/vcell/rest/VCellApiApplication.java
- vcell-api/src/main/java/org/vcell/rest/VCellApiMain.java
- vcell-api/src/main/java/org/vcell/rest/health/HealthRestlet.java
- vcell-api/src/main/java/org/vcell/rest/health/HealthService.java
- vcell-api/src/main/java/org/vcell/rest/rpc/RpcRestlet.java
- vcell-api/src/main/java/org/vcell/rest/server/RestDatabaseService.java
- vcell-apiclient/src/main/java/org/vcell/api/client/VCellApiClient.java
- vcell-apiclient/src/main/java/org/vcell/api/client/examples/VCellApiClientTest.java
- vcell-core/src/main/java/cbit/vcell/client/server/ClientServerInfo.java
- vcell-core/src/main/java/cbit/vcell/message/server/bootstrap/client/RemoteProxyVCellConnectionFactory.java
- vcell-core/src/main/java/cbit/vcell/server/VCellConnectionFactory.java
- vcell-core/src/main/java/cbit/vcell/solver/test/HybridSolverTester.java
- vcell-core/src/main/java/org/vcell/optimization/CopasiOptimizationSolver.java
- vcell-core/src/main/java/org/vcell/util/document/UserLoginInfo.java
- vcell-core/src/test/java/cbit/vcell/message/server/bootstrap/client/RemoteProxyVCellConnectionFactoryTest.java
- vcell-server/src/main/java/cbit/vcell/message/server/bootstrap/LocalVCellConnectionFactory.java
> remove all passwords from client

- vcell-api/src/main/java/org/vcell/rest/server/BiomodelOMEXServerResource.java
- vcell-api/src/main/resources/biomodel.ftl
- vcell-rest/src/main/java/org/vcell/restq/Main.java
> return HTTP 501 not implemented for /api/v0/biomodel/<id>/biomodel.omex

- vcell-cli/src/main/java/org/vcell/cli/run/OmexHandler.java
- vcell-core/src/main/java/org/jlibsedml/execution/ModelResolver.java
Allows SED-ML files with more than one master-marked SEDML to run
> Allowed multiple master sedml

- vcell-client/src/main/java/cbit/vcell/client/desktop/simulation/SimulationEditor.java
- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/LangevinOptionsPanel.java
- vcell-core/src/main/java/cbit/vcell/export/SpringSaLaDExporter.java
- vcell-core/src/main/java/cbit/vcell/mapping/ReactionRuleSpec.java
- vcell-core/src/main/java/cbit/vcell/math/VCML.java
- vcell-core/src/main/java/cbit/vcell/solver/LangevinSimulationOptions.java
- vcell-core/src/main/java/cbit/vcell/xml/XMLTags.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
- vcell-core/src/main/java/org/vcell/model/ssld/SsldUtils.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinSolver.java
Implementing the springsalad partitions concept in vcell (UI, memory representation, persistence)
testing model exchange between old springsalad app and vcell, roundtripping between the 2
> Dan ss partitions

- docker/swarm/README_zeke_stack_on_linux.md
- vcell-core/src/main/java/cbit/vcell/export/server/ExportServiceImpl.java
- vcell-core/src/main/java/cbit/vcell/export/server/N5Exporter.java
- vcell-core/src/test/java/cbit/vcell/export/N5ExporterTest.java
A bug was present which caused exports that where made in succession that had different parameter values to start reading the new parameter information.
> Export Service Implementation Holding Old State

- .github/workflows/CI-full.yml
- .github/workflows/bsts_local.yml
- .github/workflows/ci_cd.yml
- .github/workflows/create_bs_singularity.yml
- .github/workflows/site_deploy.yml
Fixes CD to use ODIC tokens, fixing current and future issues with tokens expiring
> Odic deploy fix

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/ReactionRulePropertiesTableModel.java
- vcell-core/src/main/java/cbit/vcell/mapping/NetworkTransformer.java
- vcell-core/src/main/java/cbit/vcell/model/Model.java
When a rule-based model is saved (or flattened to generate a network), the step of generating observables takes disproportionally long time.
Issue #1336
> Generation of Observables takes a long time

- vcell-cli/src/test/java/org/vcell/cli/run/hdf5/Jhdf5UtilsTest.java
- vcell-core/src/main/java/cbit/vcell/export/server/JhdfUtils.java
Adds useful convenience methods for future JHDF use
> Added convenience methods to JhdfUtils

- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularTypeSpecsTableModel.java
- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-client/src/main/java/org/vcell/util/gui/CompositeIcon.java
- vcell-client/src/main/java/org/vcell/util/gui/VCellIcons.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
Eliminated the Site column
added color icons for links to easier identify linked sites
more detailed messages for some issues
> Cosmetic changes to molecular structures and links tables

- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/SimulationSummaryPanel.java
Synchronize old "Annotations" with Formal annotations in Sims 
Issue #1408
Replaced Annotation with Description in SimulationSummaryPanel, since Annotations have their own panel
Part of hackaton2, Jan 2025
> Synchronize old "Annotations" with Formal annotations in Sims

- vcell-core/src/main/java/cbit/vcell/solver/SolverDescription.java
Integrator filtering offers unsuitable options. 
Issue #1417
Branch dan-ss-options-panel
Stricter integrator filtering for some application types based on required features.
>  Integrator filtering offers unsuitable options for SpringSaLaD applications

- vcell-core/src/main/java/cbit/vcell/solver/SolverDescription.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverFeatureSet.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverTaskDescription.java
Refactoring. Moved the SolverFeatureSet name inside the class.
Dismantling the Map since it was duplicating existing ArrayList
>  Stricter and better integrator filtering for some application types.

- vcell-core/src/main/java/cbit/vcell/solver/SolverTaskDescription.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
don't save trivial numTrials value to XML and VCML (default value is 1)
> don't save trivial numTrials value to XML and VCML

- vcell-client/src/main/java/cbit/vcell/geometry/gui/OverlayEditorPanelJAI.java
- vcell-client/src/main/java/cbit/vcell/geometry/gui/ROIMultiPaintManager.java
> Fixed bug with cropping in geometry viewer

- docker/build/vcell-admin.log4j.xml
- docker/build/vcell-api.log4j.xml
- docker/build/vcell-batch.log4j.xml
- docker/build/vcell-data.log4j.xml
- docker/build/vcell-db.log4j.xml
- docker/build/vcell-opt.log4j.xml
- docker/build/vcell-sched.log4j.xml
- docker/build/vcell-submit.log4j.xml
- vcell-rest/src/main/resources/application.properties
JSBML in debug mode throws errors so return it to INFO.
> Fix sbml debug log error

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/BioModelEditorApplicationsPanel.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/DocumentEditor.java
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
SpringSaLaD is enabled by default
> SpringSaLaD is enabled by default

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/ReactionRulePropertiesTableModel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularStructuresPropertiesPanel.java
- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/ReactionRuleSpec.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
Issue #1453, Langevin input file gets wrong particle location name
better issue message for case when Kf exceeds the diffusion limited rate.
calculate binding reaction radius for all sites
> Langevin input file gets wrong particle location name

- .github/workflows/CI-full.yml
- .github/workflows/NightlyBMDB_CLI.yml
- .github/workflows/biosimulations_cd.yml
- .github/workflows/biosimulations_verify.yml
- .github/workflows/bsts_local.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/debug.yml
- .github/workflows/nightly-model-testing.yml
- .github/workflows/site_deploy.yml
- .github/workflows/webhelp-deploy.yml
- docker/swarm/README_Apple_code_signing.md
- docker/swarm/generate_installers.sh
upon mac installer notarytool failure, request log from apple.
> add debugging to apple notarytool invocation - deploys are broken

- vcell-core/src/main/java/cbit/vcell/solvers/FiniteVolumeFileWriter.java
needed by libvcell to create a custom LocalFiniteVolumeFileWriter which can customize local field data usage
> allow overriding field data writing in FiniteVolumeFileWriter

- vcell-core/src/main/java/cbit/vcell/mapping/ReactionRuleSpec.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
Checking for physical limitations - site size, diffusion rate, partition size
> Site physical limits

- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
- vcell-core/src/test/java/cbit/vcell/util/LangevinAlgorithmsTest.java
given diffusion rate and time step, we compute what's the max distance a particle can travel with a probability P
(the particle has a P chance to stay within the calculated max displacement)
Rationale: possibility of binding is being checked only against the particles within the current and adjacent partitions (to improve performance). If a particle gets outside that volume we may miss a potential binding event
> Particle displacement for given diffusion rate, time interval and probability

- vcell-client/src/main/java/cbit/vcell/client/desktop/simulation/SimulationListTableModel.java
- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/SolverTaskDescriptionAdvancedPanel.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverTaskDescription.java
Add Steady State panel in the Simulation Options dialog
Add Steady State checkbox in the Simulation table
Only for CVODE
> Steady State UI changes

- pom.xml
Upgraded langevin solver to 1.4.4
Closes #1589
> Upgraded langevin solver to 1.4.4 - latest
