- biosimulators.json
Replaced SBO terms for hybrid methods and Smoldyn method with new terms that are more specific
- New term for hybrid stochastic continuous-discrete non-spatial framework
- New term for particle-based discrete spatial simulation
Closes #88
> Replace SBO terms with more specific ones

- vcell-cli-utils/requirements.txt
0.1.121 adds validation for NumPy dtypes. 
~~This is going to fail until I push 0.1.121 to PyPI.~~
0.1.121 should be released to PyPI in a few minutes.
> Update to biosimulators-utils 0.1.121

- vcell-cli-utils/vcell_cli_utils/status.py
- vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java
- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
- vcell-cli/src/main/java/org/vcell/cli/SolverHandler.java
The schema for logs uses `type` rather than `category`. We previously documented this incorrectly. 
A tool for validating logs is now available here. This is also now incorporated into the BioSimulators test suite.
https://api.biosimulations.org/#/Logs/LogsController_validateLog
@moraru @danv61 please merge and release another version of VCell
> fix: fixed schema for BioSimulators logs

- vcell-util/pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2021-44832
> Update log4j to 2.17.1 to address CVE-2021-44832.

- biosimulators.json
I also updated the specifications of VCell 7.4.0.38 in the BioSimulators database. With this change, the VCML language is now a menu option in the run simulation form at https://run.biosimulations.org/runs/new.
> feat: added support for VCML format to BioSimulators specifications

- vcell-cli/pom.xml
- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ConvertCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-cli/src/main/resources/log4j2.xml
- vcell-core/src/main/java/cbit/vcell/mapping/FastSystemAnalyzer.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/mapping/StructureAnalyzer.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlHelper.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLUnitTranslator.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- introduced logging (using log4j2) to replace verbose print statements in SBML/SEDML import/export classes.
- omex file validation by immediately re-reading the exported omex files to perform basic validation (omex file parse doesn't fail).
- fixed SEDML export of "initCount" parameters (for stochastic VCell applications).
- better error message for SBML export with membrane voltage.
- fixed SBML import of 2D/3D geometries with respect to subvolumes and membranes.
see https://github.com/virtualcell/vcell/issues/229
> round-trip export/import for COMBINE archives (.omex files)

- vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java
Enabling MongoDB message was causing missing properties exceptions.
> Changed MongoDB messaging property to false

- vcell-cli/src/main/java/org/vcell/cli/CLIPythonManager.java
- vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/PythonCalls.java
Turns out log files were being made, however some were missing their header and buried in a subdirectory. The header issue has been fixed, but the files can't be moved without serious refactoring of pathing in VCell CLI. In the process of fixing the header, all VCell CLI local logging functions were moved to CLIUtils.
Bonus BioSim fix refers to how error messages were obscured before by errors in the error pipeline
> Centralized log functions in VCellUtils, cleanup, and bonus BioSim fix

- vcell-cli/src/main/java/org/vcell/cli/run/OmexHandler.java
- vcell-core/src/main/java/cbit/vcell/resource/NativeLib.java
When setting up my new workstation, I came across the same native library bug I had encountered on my old system. After discovering a work around with the help of Jim, I created a simple "backup" loader in case @gmarupilla's code fails. 
This hasn't been tested on all platforms. It currently has only been tested on Linux (Ubuntu 20); Before this branch is accepted, we need confirmation that it works on:
- Windows (10)
- Mac
Once we have confirmation, we can pull this in.
When we have some time to tackle tech debt, this whole system may be moved to its own class that is called near time of execution (or at least somewhere more appropriate than buried where it is).
> added backup library loader to OmexHandler and NativeLib

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-core/src/main/java/cbit/vcell/biomodel/ModelUnitConverter.java
- vcell-core/src/main/java/cbit/vcell/mapping/AbstractStochMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/DiffEquMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/FeatureMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/MembraneMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/ParticleMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/RulebasedMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/StochMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/StructureAnalyzer.java
- vcell-core/src/main/java/cbit/vcell/mapping/potential/PotentialMapping.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionFlattenTest.java
- with symbolic KMOLE in SBML importing and exporting (or any other place where we are moving between unit systems), terms such as KMOLE/KMOLE, KMOLE * pow(KMOLE,-1), etc can accumulate and obscure the expressions for the user, and make it hard to debug for the developer.
- Expression.flattenFactors(str) was added to accompany ModelUnitConverter.getDImensionlessScaleFactor() (which introduces symbolic KMOLE as needed).
- removed a FluxReaction unit conversion from SBMLImporter.  Absolutely no unit converters should be invoked in SBMLIMporter or SBMLExporter, instead all model unit conversions should be done in ModelUnitConverter!!!
- force math generation in ModelUnitConverter following change of units.
- NOW I GET CORRECT ROUND TRIPS WITH KMOLE.
> Kmole round trip

- .github/workflows/CI-full.yml
- .github/workflows/ci_cd.yml
in CI (GitHub actions/workflows) considered introducing a separate cache action for maven dependency downloads, but found that the build-in `actions/setup-java` action has a `cache: maven` option already configured.
saves a minute or two off the of the build time in CI.
> introduce maven caching into CI-full and ci_cd workflows

- vcell-core/src/main/java/cbit/vcell/math/PdeEquation.java
- vcell-core/src/test/java/cbit/vcell/biomodel/ModelUnitConverterTest.java
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
MathOverrides required a unit conversion from VCell->SBML->VCell unit systems.  KMOLEs are used appropriately, but they were not canceled out upon round trip back into VCell.
This incomplete cancellation was due to the KMOLE 'Constant' (being ste.isConstant()==true) and KMOLE 'ReservedSymbol' (ste.isConstant()==false) behaving inconsistently during 'flatten()' - one is replaced with a number and the other one remained.
Original math override value:  22.0
After switch to SBML units: 22.0 * KMOLE
After return to VCell units: 0.0365448505 * pow(KMOLE, -1).  ~= 22.0/602 * pow(KMOLE, -1)
... should have returned to 22.0.
now it round trips back to the correct value of 22.0 and the KMOLE's cancel.
> fixed MathOverrides VCell->SBML->VCell round trip - cancels KMOLE factor

- .github/workflows/ci_cd.yml
use mvn --batch-mode to avoid progress lines showing up in CI logs.  This will make it easier to scan build and test failures and make the logs more readable.
For example:
>> mvn clean install ...
Downloading from scijava.public: https://maven.scijava.org/content/groups/public/org/scijava/pom-scijava/31.1.0/pom-scijava-31.1.0.pom
Progress (1): 4.1 kB
Progress (1): 8.2 kB
Progress (1): 12 kB 
Progress (1): 16 kB
... total of 43 'Progress' lines ...
> use 'mvn --batch-mode' to make maven logs shorter in CI (for debugging)

- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
some BioModel expressions were subject to Expression.substituteInPlace() during SBML Export (should have been cloned).  Impacted only SBMLExporter round-trip, but was poor form.
> clone orig BioModel Expressions before transforming in SBML Export

- vcell-client/src/main/java/org/vcell/util/gui/exporter/SbmlExtensionFilter.java
one-liner needed for production VCell.  round-trip validation of SBML export from VCell UI.
> validate=true for SBML export from VCell UI.

- vcell-server/src/main/java/cbit/sql/CompareDatabaseSchema.java
- vcell-server/src/main/java/cbit/sql/Field.java
- vcell-server/src/main/java/cbit/vcell/modeldb/MathVerifier.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SpeciesContextModelTable.java
In preparation for Postgres migration of VCell database, we aligned the Oracle Schema using Oracle DDL (Data Definition Language) calls (database introspection) to compare against VCell software's internal representation of the database (Java classes representing tables, fields, relationships).
A follow-up step will be to create an empty Postgres database which is aligned with the VCell software and migrate the data from Oracle to Postgres.
> Oracle schema synch to prep for Postgres

- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
SBMLExporter performs round-trip testing to make sure re-imported SBML models have and equivalent mathematical representation.  SBMLImporter chooses between non-spatial deterministic and spatial deterministic.  But while exporting stochastic applications (SimulationContexts), we must transform the SimulationContext to also be stochastic or the maths will be of different type.
This is now performed in SBMLExporter.roundTripValidation() - so we can validate the exporting and reimporting of stochastic applications.
> SBMLExporter validate compares transformed SimContext (e.g. stochastic)

- vcell-core/src/main/java/org/jlibsedml/modelsupport/SBMLSupport.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
This PR fixes all known issues for round-tripping MathOverrides in simulations from NETWORK_DETERMINISTIC applications (non-spatial and spatial):
- primary changes to SEDML import and export
- includes cherry-picked commits from @jcschaff from branch map_symbol_unitsize
It also temporarily disables the attempts to import model changes as simulation overrides for stochastic applications, which present significant problems. For stochastic applications changes are being applied to the SBML prior to import.  This has a current limitation that compute changes (which become initial assignments) are lost.
> Sedml roundtrip

- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
SourceSymbolMapping field in MathDescription was not transient, and MathSymbolMapping is not serializable (lots of assorted objects reachable by MathSymbolMapping).
field is now transient.
> fixed Not serializable exception in Simulation editor

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-core/src/main/java/cbit/vcell/geometry/SubVolume.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/cbit/vcell/xml/XMLTags.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
subvolume handles (part of Geometry, e.g. AnalyticSubVolumes) were not preserved in round-trip VCML->SBML->VCML, and default boundary condition types for structure mappings (even if no species are defined) were not preserved.  In SBML, boundary condition types are associated with each species - but VCell constrains the same boundary condition types for all species mapped to the same domain.
This PR Introduced new VCell-specific annotations to DomainTypes in SBML for SubVolume handles and boundary condition types ("Flux" or "Value" - cooresponding to "Dirichlet" or "Neumann").
This fixed several public models which did not round trip properly.  If these annotations are not present, the geometry will import fine, but the default boundary condition types are always "Flux" / "Neumann".
> round trip subvolumes handles, bcTypes, better error messages

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
remove spatial check for nonspatial compartment sizes in SEDMLExporter ... assume that the SBMLExporter already assures that this is done.  This check was placed before SBMLExporter was invoked, so it always failed.
Also, improved the nonspatial compartment size solver invocation in SBMLExporter.
> remove special check for nonspatial comp sizes in SEDMLExporter

- vcell-core/src/main/java/cbit/vcell/math/BoundaryConditionType.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
exporting Spatial SBML from VCell failed with a NullPointerException when there were unmapped compartments (eg. Features and/or Membranes which were not mapped to geometric domains.
Changes were made to tolerate incompletely mapped vcell structures (e.g. compartments).
> fix NPE when unmapped compartments exported as SBML

- vcell-client/src/main/java/cbit/vcell/mapping/gui/InitialConditionsPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/ReactionContext.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverridesResolver.java
- vcell-core/src/test/java/cbit/vcell/biomodel/ModelCountAndConcentrationTest.java
- vcell-core/src/test/resources/cbit/vcell/biomodel/ExportScanTest2_stoch_concentration.vcml
- vcell-core/src/test/resources/cbit/vcell/biomodel/ExportScanTest2_stoch_count.vcml
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionUtilsJSCLFlattenTest.java
Ion's test model with stochastic application and math overrides failed to transform initial conditions (or corresponding math overrides) between concentration and count.  This is needed for SBML/SEDML, but also just for Virtual Cell.
Added unit tests for Ion's model for concentration->count and for count->concentration transformations.
In order to simplify, ExpressionUtils.simplifyUsingJSCL() employs the basic computer algebra system JSCL which is bundled within VCell to cancel terms.  This new capability has some unit tests as well.
> Stoch count conc overrides

- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/MathOverridesTableModel.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
SEDMLImporter now properly handles all naming issues for Species initial concentrations used as targets or symbols in MathOverrides in simulations from stochastic applications.
Additional features:
- proper naming of simulations restored; should always roundtrip from VCell export and not create side effects with other SEDMLs
- name preserved on all types of Applications
- includes basic logic to merge multiple BioModels into one when Models are matchable (for future full roundtrip of BioModels with multiple applications)
Caveat: testing included many corner cases but not extensive.
> Ion overrides

- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverridesResolver.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
minor updates to Ion's work on MathOverrides (to filter unwanted MathOverrides which are distracting to the users).
- replaced hard-coded symbol names for KMOLE, Unit Factors, etc (which are not reasonably overridable) with code which refers to MathSymbolMapping to associate with reservedSymbols (e.g. KMOLE) and some MathMappingParameter (e.g. Unit factors).
- At the moment, the Simulation editor panel clones the Simulation making the above improvement impossible (the code is there, but it opts out because the information is marked as 'transient').
- The code is to be merged anyway, the logic is sound and will be invoked anywhere the Simulation is not cloned.
> smarter override filter (not used in editor) and safer iter.remove()

- vcell-api/src/main/java/org/vcell/rest/common/OverrideRepresentation.java
- vcell-api/src/main/java/org/vcell/rest/server/BiomodelSimulationSaveServerResource.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/simulation/ParameterScanPanel.java
- vcell-client/src/main/java/cbit/vcell/client/task/ClientTaskDispatcher.java
- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/MathOverridesTableModel.java
- vcell-core/src/main/java/cbit/vcell/biomodel/ModelUnitConverter.java
- vcell-core/src/main/java/cbit/vcell/mapping/AbstractMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/math/MathDescription.java
- vcell-core/src/main/java/cbit/vcell/solver/ConstantArraySpec.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlHelper.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
- vcell-core/src/test/java/cbit/vcell/solver/MathOverridesTest.java
- vcell-math/src/main/java/cbit/vcell/parser/ASTFloatNode.java
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionFlattenTest.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionUtilsJSCLFlattenTest.java
Fix MathOverride Lists and Intervals (ranges) which don't handle
- unit system changes (which need KMOLE or equivalent)
- and model transformations when changing initial concentrations <-> initial counts for stochastic applications (which need compartment size symbols and sometimes KMOLE).  
Both of these situations arise in SBML/SEDML processing.  
This work generalized MathOverride Lists and Intervals to take expressions rather than doubles, allowing incorporation of KMOLE and compartment size symbols.  Expression simplification for canceling such factors was improved significantly.
All Math Overrides now transform correctly.
List/Interval editors could be more friendly (with autocomplete for available symbols), but this is not essential now.
> Override list intervals

- vcell-math/src/main/java/cbit/vcell/parser/ASTFloatNode.java
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionUtilsJSCLFlattenTest.java
> limit expression size for JSCL simplify, fail to exp.flatten(), log t>1s

- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-core/src/main/java/cbit/vcell/mapping/MathSymbolMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/math/Variable.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
- vcell-math/src/main/java/cbit/vcell/parser/ASTFloatNode.java
- vcell-math/src/main/java/cbit/vcell/parser/ExpressionUtils.java
- vcell-math/src/main/java/cbit/vcell/parser/SymbolTableEntry.java
see #323 
fixed math override fixes which used hard-coded string templates for suffixes.  This was broken because of a syntax issue - the templates were never populated (see SimulationContext changes).
Also, sorting Variables and Bio SymbolTableEntries in the MathSymbolMapping maps makes debugging easier by sorting by Type and fully qualified identifier names.  By side effect, it may have corrected some models (where some Variables or Bio Symbols didn't behave properly as map keys (e.g. duplicate instances or bad .equals()/.hashCode() implementations).
> 323 fix override templates

- vcell-cli/src/main/java/org/vcell/cli/sbml/ModelCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ExportOmexBatchCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ExportOmexCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ModelFormat.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-client/src/main/java/org/vcell/util/gui/exporter/SedmlExtensionFilter.java
- vcell-core/src/main/java/org/vcell/sedml/ModelFormat.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
**First**, implementing new contract for SEDML/OMEX export, based on ModelFormat choice coming from GUI or CLI:
- GUI: formats mutually exclusive
- GUI: if anything fails the operation is aborted, error pops up with information on failure
- CLI: hybrid format allowable, but must be specified, by adding another entry to ModelFormat Enumeration (to be used in the future with corresponding new option in ExportOmexCommand)
- CLI: if any Application or Simulation fails, failure is logged and the processing continues if more Applications/Simulations
In the future CLI convert should use the same structured logging as CLI execute so that we have all tasks and their exceptions in json/yml for automated parsing and reporting.
**Second**, breaking down SEDMLExporter translation monster-method into …
> SEDML export refactoring, first pass - SBML format

- vcell-core/src/main/java/org/vcell/sedml/SEDMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
Parameter Scan overrides using symbolic expressions are roundtripped to SEDML via FunctionalRange.
- Both linear and logarithmic interval scans are supported
- List scans are not supported (they flattened), but:
- they can't be used in the application anyway because they can't be saved to database
- they could be supported in the future (if the ability to save is there) via piecewise functions, but it would be extremely verbose
- probably not worth it :)
Also has some import fixes related to reserved symbol parameters.
> FunctionalRange roundtrip symbolic parameter scans

- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/InitialConditionsPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/test/java/cbit/vcell/biomodel/ModelCountAndConcentrationTest.java
- vcell-server/src/main/java/cbit/vcell/modeldb/SimulationContextDbDriver.java
see.#335
made SimulationContext.setUsingConcentration() take a 'transform' flag to generate math as needed and propagate changes to the initial conditions and MathOverrides.
> SimulationContext.setUsingConcentration() auto transforms Math as needed

- vcell-core/src/main/java/cbit/vcell/mapping/AbstractMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/DiffEquMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
see #348  
fix legacy math overrides based on pattern matching - does not require model refactorying or complex transformations.
> 348 simple invalid overrides

- vcell-admin/src/main/java/org/vcell/stochtest/StochtestRunService.java
- vcell-admin/src/test/java/org/vcell/sbml/SbmlVcmlConverter.java
- vcell-admin/src/test/java/org/vcell/sbml/test/VCellSBMLSolver.java
- vcell-api/src/main/java/org/vcell/rest/common/SimulationRepresentation.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/VcmlOmexConverter.java
- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
- vcell-client/src/main/java/cbit/vcell/client/TestingFrameworkWindowManager.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/simulation/OutputFunctionsListTableModel.java
- vcell-core/src/main/java/cbit/vcell/biomodel/BioModel.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/modelopt/ModelOptimizationMapping.java
- vcell-core/src/main/java/cbit/vcell/modelopt/ModelOptimizationSpec.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/BioModelTest.java
- vcell-core/src/test/java/cbit/vcell/biomodel/ModelCountAndConcentrationTest.java
- vcell-server/src/test/java/cbit/vcell/mapping/MathGenerationHashVisitor.java
see #347 
limited simplification SimulationContext update steps - introduced BioModel.updateAll(boolean bForceUpdate) and SimulationContext.updateAll(boolean bForceUpdate).  This limited the exposure to SimulationContext.createNewMathMapping() by maybe 10-20%.  
It turns out that the majority of independent invocations of SimulationContext.createNewMathMapping() related to
1.  Swing/non-Swing threading
2. required access to the most current MathSymbolMapping
3. Customization of the process (e.g. VirtualFrap generates math and then adds to it).
> 347 biomodel update all

- vcell-core/src/main/java/cbit/vcell/biomodel/ModelUnitConverter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/ModelUnitConverterTest.java
see #362   New SBML-compatible model unit system - most SBML tools don't like a SBML substance unit of uM.um3 (which Ion pointed out is really 10^21 mol = zeptomol).
new SBML units for VCell export is familiar enough and well scaled.
substance = nmol
volume = l (litre)
area = dm2 (decimeters squared)
length = dm
volumetric concentration is in nM
surface densities are in nmol/dm^2 (where 1.0 nmol/dm^2 == 60000.0 molecules/um2)
> new default SBML-compatible unit system nmol, l, dm2, dm

- vcell-core/src/test/java/cbit/vcell/biomodel/ModelCountAndConcentrationTest.java
- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
- vcell-math/src/main/java/cbit/vcell/parser/SimpleSymbolTable.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionFlattenTest.java
see #376 
1.  Expression.simplifyJSCL() now avoids substitution of numerical values for constant symbols.
2. introduced Expression.flattenSafe() to flatten without substituting away constants (temporarily clears expression binding)
3. added good tests for bound and unbound expressions for Expression.simplifyJSCL(), .flatten(), .flattenSafe()
> fix simplifyJSCL(), introduce flattenSafe(), with tests.

- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
see #378 
major performance improvement when exporting very large biomodels to omex **_(saves 10s of seconds)_**, avoid instantiating SimulationContextOverridesResolver for every symbol request - and avoid instantiation of empty BioModel in constructor.  
[VisualVM](https://visualvm.github.io/download.html) (free Java profiling tool) was very helpful and very easy to use to diagnose this problem.
> cache and simplify MathOverride resolver - major speedup

- vcell-math/src/main/java/cbit/vcell/parser/Expression.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionFlattenTest.java
- vcell-math/src/test/java/cbit/vcell/parser/ExpressionUtilsJSCLFlattenTest.java
- vcell-math/src/test/java/cbit/vcell/parser/MathMLTester.java
see #384 
Weird symbol binding problem in many public models - eventually got to the bottom of it.
restoring Expression binding following JSCL simplification had problems.  The specialized code was replaced with a temporary symbolTable for each expression ... and rebinding the expression is simply exp.bindExpression(symbolTable).
> apply same expression rebinding after flatten() or simplifyJSCL()

- vcell-core/src/main/java/cbit/util/xml/XmlRdfUtil.java
- vcell-core/src/main/java/cbit/vcell/mapping/DiffEquMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/ParticleMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/RulebasedMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/StochMathMapping.java
see #389 
During math generation, variables are collected in a VariableHash, and then topologically sorted and set on the MathDescription all at once. For some models, new unit conversion factors are added directly to the math rather than the VariableHash, and the topological sort fails to find all dependencies.
Solution is to wait until all variables are created and stored in VariableHash before any are added to the MathDescription.
This fixes some Omex round-trip errors.
> 389 mathgen var hash

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
see #393 
MicroscopyMeasurements (e.g. convolution of spatial solution with microscope's point spread function to simulate microscopy image) is implemented in VCell as part of the MathDescription (post-processing step).
This makes any such model fail math comparison in SBML round trip.
Later, we can accommodate this situation by stripping away the MicroscopyMeasurement from the Application before exporting to SBML.
> skip SBML Export of MicroscopyMeasurements (convolutions) - part of math

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
see #395 
skipping spatial applications with lumped reactions for now.
In the future, if we want to support these models for SBML Export we must:
1. verify that SBML Export and Import are implemented correctly (must be manual for now because Math is different)
2. find a way for round-trip math to correspond (VCell uses vcRegionVolume('cyt') function to make the reaction local and after SBML round-trip the generated math does not).  There is a way to map (for spatial SBML exports) to the domain sizes which correspond one-to-one with VCell regions ... then the math should round-trip accordingly.
> spatial apps with lumped reactions: SBML Export unsupported (math fails)

- vcell-core/src/main/java/cbit/image/VCImage.java
- vcell-core/src/test/java/cbit/image/VCImageTest.java
see #399
Harmless fix for round-trip problem, however need to get to the bottom of the underlying cause and add it to the unit test.
> comparing uncompressed pixels is more robust, need to dig further

- vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
- vcell-core/src/main/java/org/jlibsedml/Libsedml.java
- vcell-core/src/main/java/org/jlibsedml/SEDMLReader.java
- vcell-core/src/main/java/org/jlibsedml/SEDMLTags.java
- vcell-core/src/main/java/org/jlibsedml/SedML.java
- vcell-core/src/main/java/org/jlibsedml/XMLException.java
- vcell-core/src/main/java/org/jlibsedml/execution/ArchiveModelResolver.java
- vcell-core/src/main/java/org/vcell/sedml/SEDMLImporter.java
This fixes a number of bugs and issues uncovered when trying to import in GUI an OMEX file produced by COPASI:
- all errors on import are silently dropped
- SEDML L1V4 not recognized as valid version
- relative URIs for model references are not resolved (GUI only - they were handled properly in CLI)
- deprecated attribute in UniformTimeCourse Simulation
This also fixes a coincidentally discovered bug of not recognizing XML files as SEDML unless specific file extension is being used (XML content type should never be assumed based on file extension, but handled exclusively via XML tags)
> Import copasi omex

- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
The nullPointerException being caused in recent versions comes down to a change from using TempSimulation to Simulation, and failing to assign a version; On linux systems, a value from this null field would be queried, and subsequently vcell would crash.
> Added temp fieldSimulationVersion to Simulation constructors

- vcell-server/src/main/java/cbit/vcell/message/server/dispatcher/SimulationStateMachine.java
- vcell-server/src/main/java/cbit/vcell/message/server/htc/HtcProxy.java
- vcell-server/src/main/java/cbit/vcell/message/server/htc/slurm/SlurmProxy.java
Kelvin has a model that demands more than 4gb of memory. We don't have a good analysis of why, but he's waiting on us for a fix. 
The plan is by adding more memory for power user requests, we can simply make Kelvin a power user and quickly give him the memory he needs without also giving everyone else that memory.
> Overriding min memory for Power users (we will add Kelvin to power users)

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
Event assignment target cannot be an assignment rule variable.
We make it initial assignment instead of an assignment rule variable during export to SBML.
> Dan assignment and event var

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
> export units to SBML as UNIT_<symbol> (e.g. Unit_s for seconds)

- vcell-core/src/main/java/org/vcell/sbml/vcell/StructureSizeSolver.java
- vcell-core/src/test/java/org/vcell/sbml/SEDMLExporterTest.java
- vcell-core/src/test/java/org/vcell/sbml/StructureSizeSolverTest.java
forgot to re-enable SEDML Export round trip test cases (almost all were disabled while debugging #491).
> Restored SEDMLExporterTest test cases (most were disabled for debugging)

- vcell-server/src/main/java/cbit/vcell/message/server/htc/slurm/SlurmProxy.java
Bugs appear to have by caused by slight syntax error. Caught an additional bug regarding library path variables.
closes #545
> Alpha Fix; swapped syntax and caught potentially empty Linking dir variable

- docker_run.sh
- vcell-cli/src/main/java/org/vcell/cli/vcml/ValidateBatchCommand.java
needed to run on Slurm which submits one file per job.  see #572
> accommodate single vcml or directory for validate

- vcell-client/src/main/java/cbit/vcell/graph/gui/ReactionCartoonEditorPanel.java
For plain models with no rules we show the "full" layout (ReactionCartoonFull) because the "molecule" layout (ReactionCartoonMolecule) is populated by shapes initialized by the random numbers generator.
However, for rule based models we'll continue to show the "molecule" layout by default, and show both layout buttons.
This fixes issue #533
> For rules select group by molecules button, for the rest select the ungrouped button

- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/cbit/vcell/mapping/StructureMapping.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/StructureSizeSolver.java
- vcell-core/src/test/java/org/vcell/sbml/StructureSizeSolverTest.java
#593 
subtle bug in expression binding caused math generation expression problem - not obvious - required very careful testing.
> bad struct mapping exp binding: fixed bad generated math sizes exps

- vcell-core/src/main/java/cbit/vcell/mapping/AbstractMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/AbstractStochMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/DiffEquMathMapping.java
- vcell-core/src/main/java/cbit/vcell/mapping/ParticleMathMapping.java
#533
VCell has a global biological namespace for species and parameters and local namespaces for locally defined reaction parameters. 
normally, we mangle the local parameters by adding a suffix related to the reaction name (e.g. "_r0") to the local name (e.g. "J") which yields "J_r0" which is typically unique. 
On rare occasion, the mangled name conflicts with another Math Symbol Name.  Given that we have no unambiguous naming scheme which protects against generated math symbol conflicts (e.g. like using fully qualified names from biological symbols), we review the putative Math Symbol names assigned to each biological entity and look for naming conflicts. 
Upon conflict, we rename the locally defined entities (e.g. local reaction parameters) using the prefix "localN_" where N counts …
> upon local/global math symbol conflicts, locals get "local_" prefix

- vcell-core/src/main/java/org/vcell/sbml/vcell/MathModel_SBMLExporter.java
see #608
hot patch for VCell_Rel (currently version 7.4.34)
> VCell_Rel 7.4 patch - fix NPE when calling SBMLDocument.printErrors() when no errors.

- vcell-client/src/main/java/org/vcell/util/gui/exporter/OmexExtensionFilter.java
- vcell-core/src/main/java/cbit/vcell/mapping/SimulationContext.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
> 653 multiple spatial validation errors

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
But not functionally equivalent.
In which case we add the "param" prefix.
> Sbml importing of a param with the same name as a reserved symbol.

- vcell-core/src/main/java/cbit/vcell/model/Kinetics.java
> Fixed renamed reaction parameters revert to predefined names on save.

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLExporter.java
> don't include unused reserved symbol in exported SBML if overridden.

- vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
see Issue #816.
This fix should fix the "simulation not found" server-side errors as well as the SQL Constraint errors sometimes found in database service.
The solution was not roll back the addition of a random simulation key which was introduced in PR #445 - will reopen #445 to find a more surgical solution to local computation with field data.
> Error message on trying to run sim (and database constraint bug)

- docker/swarm/docker-compose.yml
see #859
to accommodate vcell-sched java heap space errors on server
> set vcell-sched init/max container size from 500/1000MB to 1000/2000MB

- vcell-cli/src/main/java/org/vcell/cli/run/ExecutionJob.java
- vcell-cli/src/main/java/org/vcell/cli/run/SedmlJob.java
An artifact of the old code was deleting the temporary spatial hdf5s used in CLI to store spatial results. This ended up being a bug that was largely silent on windows because of an existing JDK bug that does not properly delete files window's is holding onto like a Jack Russell terrier. However there were catastrophic effects on unix devices.
Call has been replaced with a `deleteOnExit` call, with a warning if the OS is windows that the operation will not succeed.
closes #876 by proxy, as this is the last step.
> Fixed issue where unix systems accidentally deleted needed files too soon.

- vcell-api/src/main/java/org/vcell/rest/health/HealthService.java
see PR #896 - this PR fixes a trivial mistake (pass in non-null simulation id to retrieve data)
> small fix to previous PR, pass it propery simID to retrieve sim data.

- vcell-cli/src/main/java/org/vcell/cli/run/hdf5/Hdf5Writer.java
Fixed bug where a certain hdf5 field would not appear if the first value was null, even if some values were filled
> Fixing bug with `sedmlDataSetNames` in HDF5

- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteImpl.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecutionJob.java
- vcell-cli/src/main/java/org/vcell/cli/run/SedmlJob.java
1) An exception was thrown to indicicate models had failed, but instead caused VCell to believe it had fatally crashed.
2) vcell batch mode improperly disregarded a flag telling it to force vcell log files. Additional features to keep flushing the logs were included.
3) "bCoerceToDistributed" was passed down from start to end as a local variable, but had no impact on most functions it passed through. It's now passed to constructers only and saved as a constant instance variable (similar to the other boolean runtime options, like bKeepLogFiles)
> Fixed exception throwing, fixed vcell cli log creation option, and fixed variable passing

- .github/workflows/site_deploy.yml
- vcell-api/src/main/java/org/vcell/rest/health/HealthService.java
see #918 
use Apple's latest tool `notarytool` to notarize Macos Installers for VCell client, replacing the unsupported and soon to be discontinued `altool`.
> replace altool with notarytool in Macos installer notarization

- vcell-oracle/src/main/java/org/vcell/db/oracle/OraclePoolingConnectionFactory.java
- vcell-server/src/main/java/org/vcell/db/postgres/PostgresConnectionFactory.java
see #947, oracle drivers now assume autocommit, vcell needs to manually commit transactions.
> autocommit now defaults to true for oracle driver, vcell needs false

- vcell-core/pom.xml
see #819
brought in vcell-solver v0.0.43 (macos only) ... solver executable was incorrect.
> update macos solvers to fix local stochastic solver solutions

- docker/build/Dockerfile-admin-dev
- docker/build/Dockerfile-api-dev
- docker/build/Dockerfile-batch-dev
- docker/build/Dockerfile-data-dev
- docker/build/Dockerfile-db-dev
- docker/build/Dockerfile-sched-dev
- docker/build/Dockerfile-submit-dev
- docker/build/Dockerfile-web-dev
- docker/database/backup_scripts/README.md
- docker/database/backup_scripts/archivedb.sh
- docker/database/backup_scripts/newscn.sql
- docker/database/backup_scripts/password.txt
- docker/database/backup_scripts/run.sh
see #955
Hard coded the timezone in the Dockerfiles to New_York (will follow EDT or EST depending on time of year) for all containerized VCell services.
For the future:
1. make the container follow the host timezone
2. make VCell insensitive to time zone (e.g. client displays in local timezone or users UTC for those things that should be absolute).
> 955 database timezone

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/BioModelEditorApplicationsPanel.java
- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/DocumentEditor.java
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
> Adding enableSpringSaLaD propperty

- .github/workflows/nightly-model-testing.yml
- vcell-admin/src/main/java/org/vcell/admin/cli/AdminCLI.java
- vcell-admin/src/main/java/org/vcell/admin/cli/CLIDatabaseService.java
- vcell-admin/src/main/java/org/vcell/admin/cli/models/ModelCommands.java
- vcell-admin/src/main/java/org/vcell/admin/cli/models/ModelListCommand.java
- vcell-admin/src/main/java/org/vcell/admin/cli/models/ModelPermissionCommand.java
- vcell-cli/src/main/java/org/vcell/cli/vcml/ExportOmexBatchCommand.java
- vcell-core/src/main/java/org/vcell/util/document/BioModelInfo.java
- vcell-core/src/main/java/org/vcell/util/document/MathModelInfo.java
- vcell-server/src/main/java/cbit/vcell/modeldb/DatabaseServerImpl.java
Admin cli for model listing and permissions
vcell-su model ls
vcell-su model acl
model ls --owner=schaff:17
model ls --help
model acl --operation=add --owner=schaff:17 --user=ion:81 --biomodel-id=12600904
model acl --operation=remove --owner=schaff:17 --user=ion:81 --biomodel-id=12600904
model acl --help
> Admin CLI for model listing and ACLs

- vcell-server/src/main/java/cbit/vcell/modeldb/UserDbDriver.java
users with multiple 'special' permissions, would only be associated with one of them due to a bug in the database layer.  
Rather than processing one special permission, it should process all of them.
> parse all special user permissions instead of first

- docker/build/Dockerfile-admin-dev
- docker/build/Dockerfile-api-dev
- docker/build/Dockerfile-batch-dev
- docker/build/Dockerfile-clientgen-dev
- docker/build/Dockerfile-data-dev
- docker/build/Dockerfile-db-dev
- docker/build/Dockerfile-sched-dev
- docker/build/Dockerfile-submit-dev
- docker/build/Dockerfile-web-dev
With upgrade to java 17, the Debian base Docker images used for all vcell services did not include font support.  Installed appropriate supporting packages using apt-get.
> add missing fonts from java 17 base Docker image

- docker/swarm/vcell-services.sh
see #1051 for motivation
`vcell-services` is a bash script which is installed in `~vcell/.local/bin/vcell-services` and is in the path for user vcell.
Currently, the commands are `status` and `restart` and works for both `rel` and `alpha` sites.
> usage: vcell-services [OPTIONS] command site
> 
>   REQUIRED-ARGUMENTS
>     command          restart | status
>                         restart - restarts all services (takes optional -a | --all option)
>                         status  - shows status of all services
>     site             vcell site (e.g. rel or alpha)
>                         rel - must be run on vcellapi.cam.uchc.edu
>                         alpha - must be run on vcellapi-beta.cam.uchc.edu
> 
>   [OPTIONS]
>     -a | --all       (for restart command) restart messaging and …
> new vcell-services script

- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularTypeSpecsTableModel.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
- vcell-core/src/test/java/cbit/vcell/biomodel/SpringSaLaDGoodReactionsTest.java
In a binding reaction, the results are not correlated with the expectations if set to true
It's always false in the models built with the older SS interface. It may be an abandoned flag, I'll try to see what's going on once we start revamping the solver.
> The is2D flag is always set to false

- pom.xml
- vcell-cli/pom.xml
- vcell-core/pom.xml
- vcell-core/src/main/java/cbit/vcell/export/server/N5Specs.java
- vcell-util/pom.xml
upgraded and resolved java dependencies to fix runtime errors.  Ordinarily, maven would identify conflicts at build time, but prior `exclusions` in the maven pom file strategically forced use of newer versions of transitive dependencies that those declared.  Some exclusions were revisited, and was tested by rebuilding and running the docker-compose file locally with all services.
> fix: update runtime dependencies to resolve conflicts

- vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/SpeciesPropertiesPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/ReactionContext.java
- vcell-core/src/main/java/cbit/vcell/model/Model.java
- vcell-core/src/main/java/cbit/vcell/model/SpeciesContext.java
Changes to molecule / species (done within the biomodel UI) are now properly reflected in the species context spec of an existing application
> Editing or adding a new molecule / species is now properly addressed in existing SS application

- docker/swarm/docker-compose-small.yml
- docker/swarm/docker-compose.yml
- docker/swarm/serverconfig-uch.sh
Fixes the issue of export links being HTTP instead of HTTPS, and the errors when deploying the swarm stack because of special characters.
> Deploy s3 to swarm stack

- vcell-core/src/main/java/cbit/vcell/mapping/MolecularInternalLinkSpec.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
SpeciesContextSpec's compareEqual implementation for SpringSaLaD
Isomorphism detection for SiteAttributesSpec and MolecularInternalLinkSpec
> SpeciesContextSpec's compareEqual implementation for SpringSaLaD-specific entities

- vcell-core/src/main/java/cbit/vcell/mapping/LangevinMathMapping.java
We use the GeometricRegion to recover the correct size of the ROLE_Size StructureMappingParameter
> We use the GeometricRegion to recover the correct size of the ROLE_Size parameter

- vcell-core/src/main/java/cbit/vcell/solver/MathOverrides.java
Java iterator doesn't have the "remove" call for List iterator; Stream can filter with a lambda
> Uses streams to filter non-overridable constants rather than iterator

- vcell-core/src/main/java/cbit/vcell/export/server/N5Exporter.java
- vcell-core/src/test/java/cbit/vcell/export/N5ExporterTest.java
Previously the dimensions for exports where determined by the mesh size of simulation results, however, now it's dependent whether it's involved post-processing.
> Proper Dimensions for Postprocessed Variables

- docker/swarm/docker-compose.yml
some docker containers now run as non-root, must set the userid of the ssh secrets file to be owned by that user, or cannot access.
> fix permissions on ssh from docker

- vcell-core/src/main/java/cbit/vcell/mapping/NetworkTransformer.java
- vcell-core/src/main/java/cbit/vcell/solver/NFsimSimulationOptions.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverTaskDescription.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/main/java/org/vcell/model/ssld/SsldUtils.java
Issue #1361
Langevin jump processes located on a membrane are not being loaded from VCML
in XMLReader.getMembraneSubdomain()
because the XMLTags.LangevinParticleJumpProcessTag was ignored
properly set the MolecularType anchor elements when importing from ssld
> Membrane Langevin jump processes not loading from VCML #1361

- vcell-core/src/main/java/org/vcell/sbml/vcell/SBMLImporter.java
- vcell-core/src/test/java/org/vcell/sbml/BMDB_SBMLImportTest.java
SBML models may have reactions with id of x,y,z,t, which is not allowed in VCell.  These names are mangled now with "RESERVED_" prefix.
> mangle reserved SBML reaction names, e.g. x becomes RESERVED_x

- vcell-client/src/main/java/cbit/vcell/client/data/PDEExportDataPanel.java
- vcell-core/src/main/java/cbit/vcell/export/server/ExportServiceImpl.java
The ExportServiceImpl class declared that it required an N5 related directory which it did not need. This resulted in a required property error being thrown.
Remove that required property since it wasn't used, and make it impossible to export N5 files if the simulation is locally loaded onto a clients device.
> Fix Incapability to Export Locally Loaded Simulation Results

- pom.xml
- vcell-core/pom.xml
- vcell-core/src/main/java/cbit/vcell/export/server/ASCIIExporter.java
- vcell-core/src/main/java/cbit/vcell/export/server/JhdfUtils.java
- vcell-core/src/main/java/cbit/vcell/simdata/MultiTrialNonspatialStochSimDataReader.java
- vcell-core/src/main/java/cbit/vcell/simdata/UiTableExporterToHDF5.java
- vcell-core/src/main/java/cbit/vcell/simdata/VtkMeshGenerator.java
- vcell-core/src/test/java/cbit/vcell/resource/NativeLibTest.java
- vcell-core/src/test/java/cbit/vcell/solvers/mb/MovingBoundaryH5FileStructureTest.java
- vcell-core/src/test/java/cbit/vcell/solvers/mb/MovingBoundaryResultTest.java
- vcell-core/src/test/java/cbit/vcell/solvers/mb/MovingBoundaryVH5PathTest.java
replace use of ncsa.jhdf5 library which is not supported on Mac ARM64 machines with supported HDF5 libraries (io.jhdf and cisd.jhdf5).
- ported spatial simulation HDF5 export **writer** (using cisd.jhdf5)
- ported nonspatial stochastic multi-trial data **reader** (using io.jhdf)
- ported UiTableExporter HDF5 export **writer** (using io.jhdf)
> Replace unsupported legacy native hdf5 library

- vcell-client/src/main/java/cbit/vcell/mapping/gui/LinkSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/ModelProcessSpecsPanel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/ModelProcessSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularStructuresPropertiesPanel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularTypeSpecsTableModel.java
- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
Links are now editable, coordinates will be recalculated
Cosmetic fixes, rendering precision for coordinates and links rendering truncated to angstrom (one decimal unit)
In the table cell renderer the ColumType enum is recovered by column label instead of by column index (because some columns might have been moved around or removed at runtime)
dan-ss-links branch
> Links are now editable

- vcell-cli/src/main/java/org/vcell/cli/CLIPythonManager.java
- vcell-cli/src/main/java/org/vcell/cli/biosimulation/BiosimulationsCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecuteCommand.java
- vcell-cli/src/main/java/org/vcell/cli/run/ExecutionJob.java
- vcell-cli/src/main/java/org/vcell/cli/run/PythonCalls.java
Identified two sibling race conditions causing logs to be inaccurate under certain circumstances:
If VCell CLI ran a "heavier" simulation, it would encounter one of two different race conditions:
1) Java attempts to move the "final" log files from the temporary directory to the actual output directory, however python was not yet finished editing the file.
2) Java attempts to forcefully close the python shell it was using, before python had the chance to update the logs.
Both cases have been remedied.
> Fixes bug where logs do not properly get updated in significant size simulations.

- vcell-client/src/main/java/cbit/plot/gui/PlotPane.java
- vcell-client/src/main/java/cbit/vcell/client/FieldDataWindowManager.java
- vcell-client/src/main/java/cbit/vcell/client/data/ODEDataInterface.java
- vcell-client/src/main/java/cbit/vcell/client/data/ODEDataInterfaceImpl.java
- vcell-client/src/main/java/cbit/vcell/client/data/ODEDataViewer.java
- vcell-client/src/main/java/cbit/vcell/client/data/SimulationWorkspaceModelInfo.java
- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/ODESolverPlotSpecificationPanel.java
- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-core/src/main/java/cbit/vcell/math/ODESolverResultSetColumnDescription.java
- vcell-core/src/main/java/cbit/vcell/math/RowColumnResultSet.java
- vcell-core/src/main/java/cbit/vcell/solver/SimulationModelInfo.java
- vcell-core/src/main/java/org/vcell/model/ssld/SsldUtils.java
Filter the results of running a springsalad simulation.
The results are solver generated and are presented as linear combinations of each molecule's site bond / state pair
Also we highlight trivial result sets (where the data doesn't change)
branch: dan-ss-filter-results
> Filter springsalad simulation results

- vcell-client/src/main/java/cbit/vcell/mapping/gui/LinkSpecsTableModel.java
- vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularStructuresPropertiesPanel.java
- vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
- vcell-core/src/main/java/cbit/vcell/graph/SpeciesContextSpecLargeShape.java
- vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
selected shape highlight - site oval shape and link line shape
interactive selection updates between the sites / links table and the corresponding shapes - works both ways
> Improvements to springsalad specific properties panel and shape representation

- vcell-client/src/main/java/cbit/vcell/solver/ode/gui/LangevinOptionsPanel.java
- vcell-core/src/main/java/cbit/vcell/math/VCML.java
- vcell-core/src/main/java/cbit/vcell/solver/LangevinSimulationOptions.java
- vcell-core/src/main/java/cbit/vcell/solver/SolverTaskDescription.java
- vcell-core/src/main/java/cbit/vcell/xml/XMLTags.java
- vcell-core/src/main/java/cbit/vcell/xml/XmlReader.java
- vcell-core/src/main/java/cbit/vcell/xml/Xmlproducer.java
- vcell-core/src/main/java/org/vcell/solver/langevin/LangevinSolver.java
editing and management in the UI - in LangevinOptionsPanel
synchronization with the memory model - SolverTaskDescription and LangevinSimulationOptions (copy constructor, compareEqual)
persistence - XmlReader, XmlProducer,, VCML export / import
> numTrials and randomSeed for Langevin

- .github/workflows/webhelp-deploy.yml
Instead of using the flag which attempts to keep source file permissions, let them be whatever the target file permissions are, updating the target files time stamp in the process.
> Sync Without Attempting To Keep Origins Permissions

- vcell-rest/src/main/java/org/vcell/restq/openapi/SortApiResponsesFilter.java
The OpenAPI spec generated from Quarkus had often randomly permuted the HTTP response codes, creating non-deterministic noise in the OpenAPI spec and the generated API client code.
A filter was added to the openapi generation step in Quarkus to force the order of the APIResponses to be alphabetical (e.g. "200", "401", "403")
> add quarkus filter to sort HTTP response codes in Openapi spec

- .github/workflows/site_deploy.yml
Change the artifact version from v3 to v4.
> Fix Outdated Artifact Function Being Used

- python-restclient/README.md
- python-restclient/docs/SolverResourceApi.md
- python-restclient/vcell_client/api/solver_resource_api.py
- tools/openapi.yaml
- vcell-rest/src/main/java/org/vcell/restq/handlers/SolverResource.java
- vcell-restclient/README.md
- vcell-restclient/api/openapi.yaml
- vcell-restclient/docs/SolverResourceApi.md
- vcell-restclient/src/main/java/org/vcell/restclient/api/SolverResourceApi.java
- webapp-ng/src/app/core/modules/openapi/api/solver-resource.service.ts
The generated python client was not submitting files to the finite volume solver endpoint because the endpoint required the header 'GET'. Changed the header to 'POST' and now files are being submitted.
> Change Endpoint From 'Get' to 'Post'

- docker/build/Dockerfile-sched-dev
- docker/build/Dockerfile-submit-dev
- vcell-core/src/main/java/cbit/vcell/message/server/cmd/CommandServiceSshNative.java
- vcell-core/src/main/java/cbit/vcell/resource/PropertyLoader.java
- make ssh cmd options configurable via properties from K8s config (ControlPath option needed tweaking)
-  K8s ConfigMaps and Dockerfiles use env var `vcell_ssh_cmd_options_csv`
- Java code uses property `vcell.ssh.cmd.options.csv` 
- default value: `StrictHostKeyChecking=No,ControlMaster=auto,ControlPath=~/.ssh/%r@%h:%p,ControlPersist=1m`
- corresponding ssh option syntax: `-o StrictHostKeyChecking=No -o ControlMaster=auto -o ControlPath=~/.ssh/%r@%h:%p -o ControlPersist=1m`
> Changes to VCell to support migration to new Slurm cluster

- vcell-core/src/main/java/cbit/vcell/mapping/MathSymbolMapping.java
NullPointerException in TreeMap because of concurrent modification
Replace use of TreeMap with ConcurrentSkipListMap which is thread safe
> NullPointerException in TreeMap because of concurrent modification

- python-restclient/docs/User.md
- python-restclient/vcell_client/models/user.py
- tools/openapi.yaml
- vcell-client/src/main/java/cbit/vcell/field/gui/FieldDataGUIPanel.java
- vcell-core/src/main/java/cbit/vcell/field/FieldDataFileConversion.java
- vcell-core/src/main/java/org/vcell/util/document/User.java
- vcell-rest/src/main/java/org/vcell/restq/handlers/FieldData/FieldDataDB.java
- vcell-rest/src/main/java/org/vcell/restq/handlers/FieldData/FieldDataResource.java
- vcell-restclient/api/openapi.yaml
- vcell-restclient/docs/User.md
- vcell-restclient/src/main/java/org/vcell/restclient/model/User.java
- webapp-ng/src/app/core/modules/openapi/model/user.ts
Fixed the following bugs remaining with field data:
- Creation using a file didn't work on the Java client because the file was not being uploaded
- Error handling on the server did not delete database entries when creation failed
- When the user object was returned with an external data identifier, it did not have enough information to act as a User object on the client
> Field data hot fix

- vcell-rest/src/main/java/org/vcell/restq/handlers/AdminResource.java
- vcell-rest/src/main/java/org/vcell/restq/handlers/BioModelResource.java
- vcell-rest/src/main/java/org/vcell/restq/handlers/FieldDataResource.java
- vcell-rest/src/main/java/org/vcell/restq/handlers/PublicationResource.java
- vcell-rest/src/main/java/org/vcell/restq/handlers/SimulationResource.java
- vcell-rest/src/main/java/org/vcell/restq/handlers/UsersResource.java
- vcell-rest/src/main/java/org/vcell/restq/services/AdminRestService.java
- vcell-rest/src/main/java/org/vcell/restq/services/BioModelRestService.java
- vcell-rest/src/main/java/org/vcell/restq/services/FieldDataService.java
- vcell-rest/src/main/java/org/vcell/restq/services/PublicationService.java
- vcell-rest/src/main/java/org/vcell/restq/services/SimulationRestService.java
- vcell-rest/src/main/java/org/vcell/restq/services/UserRestService.java
- vcell-rest/src/test/java/org/vcell/restq/AdminResourceTest.java
- vcell-rest/src/test/java/org/vcell/restq/BioModelTest.java
- vcell-rest/src/test/java/org/vcell/restq/PublicationResourceTest.java
- vcell-rest/src/test/java/org/vcell/restq/apiclient/SimulationApiTest.java
The 'DB' classes weren't strictly related to the DB layer, but instead where invoking it alongside other functionality. So they are better represented by services.
> Rename DB Classes to Services

- vcell-core/src/main/java/cbit/vcell/biomodel/meta/VCMetaDataMiriamManager.java
Issue #1575 PubMed links disappeared from Annotations tabs
Fix:
PubMed is back in the Annotations Tab
Closes #1575
> PubMed links disappeared from Annotations tabs

- vcell-client/src/main/java/cbit/vcell/client/data/PDEExportDataPanel.java
A type casting error was thrown when attempting to export math models.
> Fix Math Model Export Error
